### ISSUE TITLE
Sistema de pesquisas - Função para exportar PDF na tela de respondidas

### ISSUE THREAD

**Issue by princebsb** [UNICEF01/BuscaAtiva#1023]

**Comment by manoelsouzaunicef** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1023?planning-poker) with Zenhub @ricardosreichert @manoelsouzaunicef
