### ISSUE TITLE
Cidade estado - Filtro cidade na lista de casos do município

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1083]

**Comment by princebsb** [comment]
Foi feita alteração na API para fazer o filtro dos municípios, na tela da Children do BAE.

https://images.zenhubusercontent.com/611c0068dbca9d06e4c13e80/6bdf9440-d23f-4dab-b47e-1d70ee74f2a5

**Comment by manoelsouzaunicef** [comment]
implementar um seletor de cidades - api não está retornando 100%

**Comment by princebsb** [comment]
Alteração para implementar um seletor de uf e cidades
