### ISSUE TITLE
Cidade estado - Filtro cidade na lista de escolas localizadas na importação do educacenso

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1085]

**Comment by manoelsouzaunicef** [comment]
**Verificar como definir uma escola municipal e estadual.**
As escolas registradas no sistema não são apenas municipais como foi afirmado nas reuniões. Logo, esse sistema de convites para fornecimento de endereços e o sistema para controle de frequências precisa ser revisto.

**As escolas são usadas nos seguintes pontos:**
- Etapa de rematrícula: Indicação da cidade onde a criança vai estudar;
- Etapa de pesquisa: onde a criança estudava;
- Importação do Educacenso: Agrupamento de crianças por escola para envio do email e preenchimento do endereço;
- Controle de frequências

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1085?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by manoelsouzaunicef** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1085?planning-poker) with Zenhub @ricardosreichert

**Comment by manoelsouzaunicef** [comment]
**Antes**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlBoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6c74ff0464bde4a0c1e8ee7ceedf34affa8ddeeb/antes.jpg)

**Depois**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlhoQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--eb06da47080d6731d48fef0689b561229da91219/depois.jpg)
