### ISSUE TITLE
Cidade estado - FRONT - Coluna grupo na lista de alertas pendentes

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1101]

**Comment by princebsb** [comment]
Houve uma mudança para adicionar um tooltip informando a cadeia de dependência do grupo.

![image.png](https://images.zenhubusercontent.com/611c0068dbca9d06e4c13e80/9939a040-b657-4942-92df-eefdf1afc4f5)
