### ISSUE TITLE
Cidade estado - Script para update de todos os casos sem grupos

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1116]
Casos que estão sob a supervisão de um usuário serão atribuídos ao grupo do usuário;
	Para usuários cancelados -> encaminhar para o grupo principal
	Para usuários sem grupo -> encaminhar para o grupo principal

**Essa ação deverá editar os alertas (todos sem grupos)**

**Comment by rafaelecs1** [comment]
Tarefa dividida em 2 partes.

1.  - adicionar ao grupo principal os casos que não tenham usuário responsável. done
2. - adicionar ao grupo do usuário:
2.1 - verificar se o usuário não foi desativado. Caso sim, mandar para o grupo principal. done
2.2 - verificar se o grupo do usuário não foi desativado. Caso sim, mandar para o grupo principal.
2.3 - manda para o grupo do usuário responsável.
2.4 - Mandar para o grupo principal do município os casos que estiverem sob responsabilidade de um usuário estadual. (?)
