### ISSUE TITLE
Cidade-estado - Edição de usuários com casos em andamento

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1134]
Para edição de usuários com casos:
**SOMENTE PARA QUANDO HOUVER ALTERACAO DO GRUPO DO USUÁRIO A SER EDITADO**
- Casos permanecem nos grupos;
- Caso fica pendente de atribuição.

**Comment by manoelsouzaunicef** [comment]
Caso fica pendente de atribuição em qualquer tipo de troca de grupos? Ou apenas para aqueles que não fazem parte dos nós?

**Comment by rafaelecs1** [comment]
Está limitado a 400 reindex, verificar o porquê disso.
