### ISSUE TITLE
Cidade-estado - Permitir o movimento de casos em grande quantidade

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1137]
A ideia é permitir que o usuário selecione uma lista de casos e os transfira para um grupo específico
![movimento de casos em grupo.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/1db360ab-b997-4308-b70e-cb83898f19d4)

**Comment by rafaelecs1** [comment]
Quando selecionado muitos casos, acontece erro. verificar o motivo e melhorar isso.
