### ISSUE TITLE
Cidade-estado - Carregar grupos da cidade do usuário de acordo com o email, uf e cidade informados na tela de criacao de alertas

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1138]
A página **https://alerta.buscaativaescolar.org.br** não exige o login do usuário portanto não acessa os grupos. A API neste caso apenas recebe os dados e, de acordo com email, UF e cidade, cria o alerta. A issue aqui é colocar um seletor de grupos de acordo com o email, uf e cidade informados no formulário deixando como default o grupo ao qual o agente comunitário (ou outro usuário) pertence.

![alertabuscaativapage.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/800e415c-ef04-42de-ad15-cfc427e8903d)

**Comment by rafaelecs1** [comment]
O alerta irá pro grupo do agente que estiver registrando o caso.
