### ISSUE TITLE
Cidade-estado - Carregar grupos da cidade no APP da BAE

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1139]

**Comment by rafaelecs1** [comment]
Tarefa não tem como ser realizada. Todos os grupos criados aqui serão enviados pro grupo principal.

**Comment by manoelsouzaunicef** [comment]
Editamos a rota principal da API onde recebe alertas para definir o grupo padrão do município quando o alerta que provém do SMS ou APP não tem indicação de grupos
