### ISSUE TITLE
Cidade-estado - Script para geração de cidade estado com grupos e subgrupos

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1190]

**Comment by manoelsouzaunicef** [comment]
Script pode ser executado na pasta da API no servidor:

**php artisan test:criando_cidade_estado**

O script solicita o nome da cidade, UF, Código IBGE da UF, dados do Prefeito, Gestor e Coordenador. Cria um tenant signup, tenant, city e usuários coordenador e gestor. 
Gera a seguinte estrutura de grupos:
Regional 1 -> Cidade -> Escola. (Com todas as cidades e escolas da UF informada)

https://github.com/UNICEF01/busca-ativa-escolar-api/commit/6aad5d6d3b9022bc9dc7e3552912193f335ccd22

**Comment by rafaelecs1** [comment]
Automatizei o processo. Com isso serão geradas as cidades, adesões municipais, município, 2 usuários genéricos (um coordenador e o gestor político), grupo primário Secretaria Estadual de Educação, uma regional 1 genérica, os municípios como nível 3 com suas respectivas escolas como grupos nível 4. Todos os coordenadores e gestores estão com lgpd sem estar aceita. Isso se deve ao fato que quando os estados enviarem as pessoas que ficarão responsáveis pelo cargo deverão aceitar o termo.

**Comment by rafaelecs1** [comment]
Criado  o script que gera os grupos dos municípios levando a regra:
Secretaria Municipal de Educação -> DRE 1 -> Secretaria 1 -> Escolas.

Criado script que porta todos usuários e casos para a Secretaria Municipal de Educação.
