### ISSUE TITLE
Melhoria adesões municipais

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#123]
Ambiente: oficial
Aba: adesões municipais

Fazer com que o status de entrada/automático seja o "todos" (atualmente está o "aguardando configuração").

Também, alterar as cores de fundo dos status "aprovado e configurado" e "rejeitado" para facilitar a visualização.

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/51981837-5f4d7580-247b-11e9-8e58-4af2405df83a.png)

**Comment by manoelsouzaunicef** [comment]
Equipe manteve o status aguardando configuração
