### ISSUE TITLE
Formulário de alerta e pesquisa em PDF

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#124]
Incluir novos campos no formulário de pesquisa em formato PDF e trocar o arquivo disponibilizado no site

**Comment by sandyunicef** [comment]
Serviço feito por terceiros @Vilmar72 @manoelsouzaunicef

**Comment by sandyunicef** [comment]
Incluir Dimensão Raca/Cor - sem informacao
Incluir Dimensão Atividade econômica - sem informacao
Incluir Dimensão escolaridade do responsável - Exibir e sem informacao
Para renda incluir nome sem informação - sem informacao
Retirar o item sem informação do relatório
Sexo - remover filtro de sem informacao
