### ISSUE TITLE
Contador de tempo

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#125]
Parece-me que a contagem tempo do tempo decorrido da adesão está com problemas...

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/52063954-bd9d5580-255a-11e9-93bb-e39ddc50b870.png)

**Comment by danielbarboni** [comment]
Implementar dealhamento maior. Ao invés de informar "há 2 anos", informar "há 1A3M45D "
