### ISSUE TITLE
Seta de ordenação não funciona coluna status

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#126]

**Comment by biancacambiaghi** [comment]
![Slide1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d2ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98b15be04be28824b82bfbc824ac6e02f68.JPG)

**Comment by biancacambiaghi** [comment]
![Slide2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d1ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98515be04be28824b82bfbe8e44c3e02f68.JPG)

**Comment by biancacambiaghi** [comment]
A lista de casos não se altera mesmo mudando o filtro de status

**Comment by danielbarboni** [comment]
Iremos verificar e sendo procedente a feature entrará na próxima sprint como Bug Fix.
