### ISSUE TITLE
Cidade-estado: Migration e Modelo para tabela notificações

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1266]
Cria nova migration para registro das seguintes informações:

- Data
- Usuário (que criou)
- Anotação
- Notificados (usuários do tree_id do caso)

Verificar o nome mais adequado para a tabela. O termo **notifications** já é usado pelo sistema de notificações do laravel

**Comment by rafaelecs1** [comment]
Notificados (usuários do tree_id do caso) Não há necessidade ao meu ver.

**Comment by rafaelecs1** [comment]
Criado a interface, repositório, serviço, migration, model, controller, rota.
Criado as regras para permitir a visualização e edição das notificações.
Atualização de todos os pontos da api que utilizam tree_id.
Atualização da página das notificações.
