### ISSUE TITLE
Criação de novo nó no Elastic Search para absorver os dados consolidados do nó que contém o histórico completo

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#1363]
1) Criar um novo nó para dados consolidados.
2) Dentro deste nó, criar um documento para cada município.
3) Cada documento de cada município deverá conter para cada dia, os dados consolidados para cada dimensão dos dados da criança (Status do Caso, Etapa do Caso, Faixa Etária, Sexo, etc.).
4) Criar um documento que agrupe os dados consolidados dos municípios de cada estado, cada região (N, S, NE, CO, SE), cada território UNICEF (Semiárido, Amazônia Legal, UAPI, PCU, etc.), e nacional.

**Comment by manoelsouzaunicef** [comment]
Campos identificados que serão usados no novo índice:

id
date
tenant_id
tenant_region
tenant_uf
tenant_name
tenant_ibge_id
child_uf
alert_status_accepted
alert_status_rejected
alert_status_pending
case_cancelled
case_completed
case_in_observation
case_in_progress
case_in_school
case_interrupted
case_out_of_school
case_transferred
step_alerta
step_pesquisa
step_analise_tecnica
step_gestao_do_caso
step_rematricula
step_1a_observacao
step_2a_observacao
step_3a_observacao
step_4a_observacao
age_null
age_0_4
age_4_5
age_6_10
age_11_14
age_15_17
age_18_more
gender_null
gender_male
gender_female
parents_income_null
parents_income_between_one_and_two
parents_income_between_quarter_and_half
parents_income_over_2
parents_income_up_to_quarter
place_kind_null
place_kind_rural
place_kind_urban
work_activity_null
work_activity_negocio_familiar
work_activity_servico_domestico
work_activity_other
case_cause_ids_null
case_cause_ids_10
case_cause_ids_21
case_cause_ids_22
case_cause_ids_23
case_cause_ids_24
case_cause_ids_25
case_cause_ids_30
case_cause_ids_40
case_cause_ids_50
case_cause_ids_60
case_cause_ids_61
case_cause_ids_70
case_cause_ids_71
case_cause_ids_72
case_cause_ids_80
case_cause_ids_91
case_cause_ids_92
case_cause_ids_100
case_cause_ids_101
case_cause_ids_102
case_cause_ids_103
case_cause_ids_110
case_cause_ids_120
case_cause_ids_130
case_cause_ids_140
case_cause_ids_150
case_cause_ids_161
case_cause_ids_162
case_cause_ids_163
case_cause_ids_164
case_cause_ids_165
case_cause_ids_166
case_cause_ids_167
case_cause_ids_170
case_cause_ids_180
case_cause_ids_500
case_cause_ids_600
alert_cause_id_10
alert_cause_id_20
alert_cause_id_30
alert_cause_id_40
alert_cause_id_50
alert_cause_id_60
alert_cause_id_61
alert_cause_id_70
alert_cause_id_80
alert_cause_id_90
alert_cause_id_100
alert_cause_id_110
alert_cause_id_111
alert_cause_id_120
alert_cause_id_130
alert_cause_id_140
alert_cause_id_150
alert_cause_id_160
alert_cause_id_170
alert_cause_id_180
alert_cause_id_500
alert_cause_id_600
race_null
race_amarela
race_branca
race_indigena
race_negra_pretos_e_pardos
race_parda
race_preta
race_no_info
guardian_schooling_null
guardian_schooling_ef_completo
guardian_schooling_ef_incompleto
guardian_schooling_em_completo
guardian_schooling_em_incompleto
guardian_schooling_nenhuma
guardian_schooling_posgraduacao
guardian_schooling_superior_completo
guardian_schooling_superior_incompleto
school_last_grade_creche_1ano
school_last_grade_creche_2ano
school_last_grade_creche_3ano
school_last_grade_creche_4ano
school_last_grade_preescola_4anos
school_last_grade_preescola_5anos
school_last_grade_ef_1ano
school_last_grade_ef_2ano
school_last_grade_ef_3ano
school_last_grade_ef_4ano
school_last_grade_ef_5ano
school_last_grade_ef_6ano
school_last_grade_ef_7ano
school_last_grade_ef_8ano
school_last_grade_ef_9ano
school_last_grade_em_1ano
school_last_grade_em_2ano
school_last_grade_em_3ano
school_last_grade_eja_finais
school_last_grade_eja_iniciais
school_last_grade_eja_alfabetizado

**Comment by manoelsouzaunicef** [comment]
![novo_indice.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/d749b1d6-c866-401c-aff7-db86fb34c6d6)
_Ambiente de testes_

Verificar com a equipe as demais classificações dos municípios usadas pelo UNICEF (SELO, Territórios ..!

**Comment by manoelsouzaunicef** [comment]
Script para teste de inserção de dados:

#!/bin/bash
# array com cidades

for (( j=0; j<6568; j++ ));
do
	curl -XPUT http://localhost:9200/tenants_daily/tenant/$j -d '{
		"type": "city",
		"date": "2023-01-18",
		"tenant_id": 1,
		"tenant_region": "NO",
		"tenant_uf": "BA",
		"tenant_name": "name_city",
		"tenant_ibge_id": 1237865,
		"alert_status_accepted": 10,
		"alert_status_rejected": 10,
		"alert_status_pending": 10,
		"case_cancelled": 10,
		"case_completed": 10,
		"case_in_observation": 10,
		"case_in_progress": 10,
		"case_in_school": 10,
		"case_interrupted": 10,
		"case_out_of_school": 10,
		"case_transferred": 10,
		"step_alerta": 10,
		"step_pesquisa": 10,
		"step_analise_tecnica": 10,
		"step_gestao_do_caso": 10,
		"step_rematricula": 10,
		"step_1a_observacao": 10,
		"step_2a_observacao": 10,
		"step_3a_observacao": 10,
		"step_4a_observacao": 10,
		"age_null": 10,
		"age_0_4": 10,
		"age_4_5": 10,
		"age_6_10": 10,
		"age_11_14": 10,
		"age_15_17": 10,
		"age_18_more": 10,
		"gender_null": 10,
		"gender_male": 10,
		"gender_female": 10,
		"parents_income_null": 10,
		"parents_income_between_one_and_two": 10,
		"parents_income_between_quarter_and_half": 10,
		"parents_income_over_2": 10,
		"parents_income_up_to_quarter": 10,
		"place_kind_null": 10,
		"place_kind_rural": 10,
		"place_kind_urban": 10,
		"work_activity_null": 10,
		"work_activity_negocio_familiar": 10,
		"work_activity_servico_domestico": 10,
		"work_activity_other": 10,
		"case_cause_ids_null": 10,
		"case_cause_ids_10": 10,
		"case_cause_ids_21": 10,
		"case_cause_ids_22": 10,
		"case_cause_ids_23": 10,
		"case_cause_ids_24": 10,
		"case_cause_ids_25": 10,
		"case_cause_ids_30": 10,
		"case_cause_ids_40": 10,
		"case_cause_ids_50": 10,
		"case_cause_ids_60": 10,
		"case_cause_ids_61": 10,
		"case_cause_ids_70": 10,
		"case_cause_ids_71": 10,
		"case_cause_ids_72": 10,
		"case_cause_ids_80": 10,
		"case_cause_ids_91": 10,
		"case_cause_ids_92": 10,
		"case_cause_ids_100": 10,
		"case_cause_ids_101": 10,
		"case_cause_ids_102": 10,
		"case_cause_ids_103": 10,
		"case_cause_ids_110": 10,
		"case_cause_ids_120": 10,
		"case_cause_ids_130": 10,
		"case_cause_ids_140": 10,
		"case_cause_ids_150": 10,
		"case_cause_ids_161": 10,
		"case_cause_ids_162": 10,
		"case_cause_ids_163": 10,
		"case_cause_ids_164": 10,
		"case_cause_ids_165": 10,
		"case_cause_ids_166": 10,
		"case_cause_ids_167": 10,
		"case_cause_ids_170": 10,
		"case_cause_ids_180": 10,
		"case_cause_ids_500": 10,
		"case_cause_ids_600": 10,
		"alert_cause_id_10": 10,
		"alert_cause_id_20": 10,
		"alert_cause_id_30": 10,
		"alert_cause_id_40": 10,
		"alert_cause_id_50": 10,
		"alert_cause_id_60": 10,
		"alert_cause_id_61": 10,
		"alert_cause_id_70": 10,
		"alert_cause_id_80": 10,
		"alert_cause_id_90": 10,
		"alert_cause_id_100": 10,
		"alert_cause_id_110": 10,
		"alert_cause_id_111": 10,
		"alert_cause_id_120": 10,
		"alert_cause_id_130": 10,
		"alert_cause_id_140": 10,
		"alert_cause_id_150": 10,
		"alert_cause_id_160": 10,
		"alert_cause_id_170": 10,
		"alert_cause_id_180": 10,
		"alert_cause_id_500": 10,
		"alert_cause_id_600": 10,
		"race_null": 10,
		"race_amarela": 10,
		"race_branca": 10,
		"race_indigena": 10,
		"race_negra_pretos_e_pardos": 10,
		"race_parda": 10,
		"race_preta": 10,
		"race_no_info": 10,
		"guardian_schooling_null": 10,
		"guardian_schooling_ef_completo": 10,
		"guardian_schooling_ef_incompleto": 10,
		"guardian_schooling_em_completo": 10,
		"guardian_schooling_em_incompleto": 10,
		"guardian_schooling_nenhuma": 10,
		"guardian_schooling_posgraduacao": 10,
		"guardian_schooling_superior_completo": 10,
		"guardian_schooling_superior_incompleto": 10,
		"school_last_grade_creche_1ano": 10,
		"school_last_grade_creche_2ano": 10,
		"school_last_grade_creche_3ano": 10,
		"school_last_grade_creche_4ano": 10,
		"school_last_grade_preescola_4anos": 10,
		"school_last_grade_preescola_5anos": 10,
		"school_last_grade_ef_1ano": 10,
		"school_last_grade_ef_2ano": 10,
		"school_last_grade_ef_3ano": 10,
		"school_last_grade_ef_4ano": 10,
		"school_last_grade_ef_5ano": 10,
		"school_last_grade_ef_6ano": 10,
		"school_last_grade_ef_7ano": 10,
		"school_last_grade_ef_8ano": 10,
		"school_last_grade_ef_9ano": 10,
		"school_last_grade_em_1ano": 10,
		"school_last_grade_em_2ano": 10,
		"school_last_grade_em_3ano": 10,
		"school_last_grade_eja_finais": 10,
		"school_last_grade_eja_iniciais": 10,
		"school_last_grade_eja_alfabetizado": 10
	}'
done

echo "FIM"

**Comment by manoelsouzaunicef** [comment]
**Documento atualizado para a versão abaixo:**

**type** define o tipo (nacional, regional, estadual, municipal)
**uf_name** somente para tipo estadual
**region_name** somente para tipo regional
**tenant_** com com este prefixo somente para municípios
{
    "settings": {
        "number_of_replicas": 0
    },
    "mappings": {
        "tenant": {
            "properties": {
                "type": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "id": {
                    "type": "string",
                    "index": "not_analyzed"
                },
                "date": {
                    "type": "date",
                    "format": "date",
                    "store": true
                },
                "uf_name": {
                    "type": "string"
                },
                "region_name": {
                    "type": "string"
                },
                "tenant_id": {
                    "type": "string"
                },
                "tenant_region": {
                    "type": "string"
                },
                "tenant_uf": {
                    "type": "string"
                },
                "tenant_name": {
                    "type": "string"
                },
                "tenant_ibge_id": {
                    "type": "integer"
                },
                "alert_status_accepted": {
                    "type": "integer"
                },
                "alert_status_rejected": {
                    "type": "integer"
                },
                "alert_status_pending": {
                    "type": "integer"
                },
                "case_cancelled": {
                    "type": "integer"
                },
                "case_completed": {
                    "type": "integer"
                },
                "case_in_observation": {
                    "type": "integer"
                },
                "case_in_progress": {
                    "type": "integer"
                },
                "case_in_school": {
                    "type": "integer"
                },
                "case_interrupted": {
                    "type": "integer"
                },
                "case_out_of_school": {
                    "type": "integer"
                },
                "case_transferred": {
                    "type": "integer"
                },
                "step_alerta": {
                    "type": "integer"
                },
                "step_pesquisa": {
                    "type": "integer"
                },
                "step_analise_tecnica": {
                    "type": "integer"
                },
                "step_gestao_do_caso": {
                    "type": "integer"
                },
                "step_rematricula": {
                    "type": "integer"
                },
                "step_1a_observacao": {
                    "type": "integer"
                },
                "step_2a_observacao": {
                    "type": "integer"
                },
                "step_3a_observacao": {
                    "type": "integer"
                },
                "step_4a_observacao": {
                    "type": "integer"
                },
                "age_null": {
                    "type": "integer"
                },
                "age_0_4": {
                    "type": "integer"
                },
                "age_4_5": {
                    "type": "integer"
                },
                "age_6_10": {
                    "type": "integer"
                },
                "age_11_14": {
                    "type": "integer"
                },
                "age_15_17": {
                    "type": "integer"
                },
                "age_18_more": {
                    "type": "integer"
                },
                "gender_null": {
                    "type": "integer"
                },
                "gender_male": {
                    "type": "integer"
                },
                "gender_female": {
                    "type": "integer"
                },
                "parents_income_null": {
                    "type": "integer"
                },
                "parents_income_between_one_and_two": {
                    "type": "integer"
                },
                "parents_income_between_quarter_and_half": {
                    "type": "integer"
                },
                "parents_income_over_2": {
                    "type": "integer"
                },
                "parents_income_up_to_quarter": {
                    "type": "integer"
                },
                "place_kind_null": {
                    "type": "integer"
                },
                "place_kind_rural": {
                    "type": "integer"
                },
                "place_kind_urban": {
                    "type": "integer"
                },
                "work_activity_null": {
                    "type": "integer"
                },
                "work_activity_negocio_familiar": {
                    "type": "integer"
                },
                "work_activity_servico_domestico": {
                    "type": "integer"
                },
                "work_activity_other": {
                    "type": "integer"
                },
                "case_cause_ids_null": {
                    "type": "integer"
                },
                "case_cause_ids_10": {
                    "type": "integer"
                },
                "case_cause_ids_21": {
                    "type": "integer"
                },
                "case_cause_ids_22": {
                    "type": "integer"
                },
                "case_cause_ids_23": {
                    "type": "integer"
                },
                "case_cause_ids_24": {
                    "type": "integer"
                },
                "case_cause_ids_25": {
                    "type": "integer"
                },
                "case_cause_ids_30": {
                    "type": "integer"
                },
                "case_cause_ids_40": {
                    "type": "integer"
                },
                "case_cause_ids_50": {
                    "type": "integer"
                },
                "case_cause_ids_60": {
                    "type": "integer"
                },
                "case_cause_ids_61": {
                    "type": "integer"
                },
                "case_cause_ids_70": {
                    "type": "integer"
                },
                "case_cause_ids_71": {
                    "type": "integer"
                },
                "case_cause_ids_72": {
                    "type": "integer"
                },
                "case_cause_ids_80": {
                    "type": "integer"
                },
                "case_cause_ids_91": {
                    "type": "integer"
                },
                "case_cause_ids_92": {
                    "type": "integer"
                },
                "case_cause_ids_100": {
                    "type": "integer"
                },
                "case_cause_ids_101": {
                    "type": "integer"
                },
                "case_cause_ids_102": {
                    "type": "integer"
                },
                "case_cause_ids_103": {
                    "type": "integer"
                },
                "case_cause_ids_110": {
                    "type": "integer"
                },
                "case_cause_ids_120": {
                    "type": "integer"
                },
                "case_cause_ids_130": {
                    "type": "integer"
                },
                "case_cause_ids_140": {
                    "type": "integer"
                },
                "case_cause_ids_150": {
                    "type": "integer"
                },
                "case_cause_ids_161": {
                    "type": "integer"
                },
                "case_cause_ids_162": {
                    "type": "integer"
                },
                "case_cause_ids_163": {
                    "type": "integer"
                },
                "case_cause_ids_164": {
                    "type": "integer"
                },
                "case_cause_ids_165": {
                    "type": "integer"
                },
                "case_cause_ids_166": {
                    "type": "integer"
                },
                "case_cause_ids_167": {
                    "type": "integer"
                },
                "case_cause_ids_170": {
                    "type": "integer"
                },
                "case_cause_ids_180": {
                    "type": "integer"
                },
                "case_cause_ids_500": {
                    "type": "integer"
                },
                "case_cause_ids_600": {
                    "type": "integer"
                },
                "alert_cause_id_10": {
                    "type": "integer"
                },
                "alert_cause_id_20": {
                    "type": "integer"
                },
                "alert_cause_id_30": {
                    "type": "integer"
                },
                "alert_cause_id_40": {
                    "type": "integer"
                },
                "alert_cause_id_50": {
                    "type": "integer"
                },
                "alert_cause_id_60": {
                    "type": "integer"
                },
                "alert_cause_id_61": {
                    "type": "integer"
                },
                "alert_cause_id_70": {
                    "type": "integer"
                },
                "alert_cause_id_80": {
                    "type": "integer"
                },
                "alert_cause_id_90": {
                    "type": "integer"
                },
                "alert_cause_id_100": {
                    "type": "integer"
                },
                "alert_cause_id_110": {
                    "type": "integer"
                },
                "alert_cause_id_111": {
                    "type": "integer"
                },
                "alert_cause_id_120": {
                    "type": "integer"
                },
                "alert_cause_id_130": {
                    "type": "integer"
                },
                "alert_cause_id_140": {
                    "type": "integer"
                },
                "alert_cause_id_150": {
                    "type": "integer"
                },
                "alert_cause_id_160": {
                    "type": "integer"
                },
                "alert_cause_id_170": {
                    "type": "integer"
                },
                "alert_cause_id_180": {
                    "type": "integer"
                },
                "alert_cause_id_500": {
                    "type": "integer"
                },
                "alert_cause_id_600": {
                    "type": "integer"
                },
                "race_null": {
                    "type": "integer"
                },
                "race_amarela": {
                    "type": "integer"
                },
                "race_branca": {
                    "type": "integer"
                },
                "race_indigena": {
                    "type": "integer"
                },
                "race_negra_pretos_e_pardos": {
                    "type": "integer"
                },
                "race_parda": {
                    "type": "integer"
                },
                "race_preta": {
                    "type": "integer"
                },
                "race_no_info": {
                    "type": "integer"
                },
                "guardian_schooling_null": {
                    "type": "integer"
                },
                "guardian_schooling_ef_completo": {
                    "type": "integer"
                },
                "guardian_schooling_ef_incompleto": {
                    "type": "integer"
                },
                "guardian_schooling_em_completo": {
                    "type": "integer"
                },
                "guardian_schooling_em_incompleto": {
                    "type": "integer"
                },
                "guardian_schooling_nenhuma": {
                    "type": "integer"
                },
                "guardian_schooling_posgraduacao": {
                    "type": "integer"
                },
                "guardian_schooling_superior_completo": {
                    "type": "integer"
                },
                "guardian_schooling_superior_incompleto": {
                    "type": "integer"
                },
                "school_last_grade_creche_1ano": {
                    "type": "integer"
                },
                "school_last_grade_creche_2ano": {
                    "type": "integer"
                },
                "school_last_grade_creche_3ano": {
                    "type": "integer"
                },
                "school_last_grade_creche_4ano": {
                    "type": "integer"
                },
                "school_last_grade_preescola_4anos": {
                    "type": "integer"
                },
                "school_last_grade_preescola_5anos": {
                    "type": "integer"
                },
                "school_last_grade_ef_1ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_2ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_3ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_4ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_5ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_6ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_7ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_8ano": {
                    "type": "integer"
                },
                "school_last_grade_ef_9ano": {
                    "type": "integer"
                },
                "school_last_grade_em_1ano": {
                    "type": "integer"
                },
                "school_last_grade_em_2ano": {
                    "type": "integer"
                },
                "school_last_grade_em_3ano": {
                    "type": "integer"
                },
                "school_last_grade_eja_finais": {
                    "type": "integer"
                },
                "school_last_grade_eja_iniciais": {
                    "type": "integer"
                },
                "school_last_grade_eja_alfabetizado": {
                    "type": "integer"
                },
                "region_n": {
                    "type": "integer"
                },
                "region_s": {
                    "type": "integer"
                },
                "region_co": {
                    "type": "integer"
                },
                "region_se": {
                    "type": "integer"
                },
                "region_no": {
                    "type": "integer"
                }
            }
        }
    }
}
