### ISSUE TITLE
BAE Cadastrar campos comunidade quilombola, ribeirinho e indígena

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1378]
A tabela **case_steps_pesquisa** já possui um campo chamado **place_is_quilombola** que corresponde ao seguinte campo no formulário:

![quilombola.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/623ffdf1-f3d5-48e7-ad07-7e15d3bb3f41)

3 novos campos já estão registrados mesma tabela e não estão sendo utilizados:
**place_is_indigena
place_is_do_campo
place_is_ribeirinha**
Não há necessidade de nova migration

A tarefa consiste em criar uma lista de radio buttons onde cada opção corresponde a um desses valores.
- Colocar um campo extra no formulário apenas para indicar se pertence a uma comunidade específica. Em caso de true, obrigar a seleção em um dos 4 radio buttons.
- Verificar momento de edição. Os campos já devem aparecer preenchidos caso algum tenha sido selecionado. Inclusive o **comunidade específica**
- Verificar o JSON que fornece o formulário para o APP;
- Verificar processo de reindexação para registro de novos campos;
- Verificar necessidade de mapping do índice do elasticsearch para o registro dos novos campos;

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1378?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by ricardosreichert** [comment]
@manoelsouzaunicef Por favor, realize um teste da implementação.
https://github.com/UNICEF01/busca-ativa-escolar-web/commit/7f23a14316723d4892fa0adc1ce8b6b83cbc6bd4
