### ISSUE TITLE
Verificar importação de escolas antes da importação de evadidos

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#139]
Item 4: Somente é possível importar os alertas de um novo ano, após a importação nossa da planilha nova de escolas do referido ano.

**Comment by biancacambiaghi** [comment]
Tenho uma dúvida quanto à essa atualização da lista de escolas. Como é feita? No início do ano o INEP passa pra vocês uma lista atualizada e vocês atualizam a plataforma?  Ou isso ocorre mais vezes (1x por semestre ou sempre que há alteração (inclusão / fechamento) de escolas)?

**Comment by manoelsouzaunicef** [comment]
Fizemos a atualizacao da lista assim que o INEP liberou as lista do Educacenso 2018. A atualizacao é fita a cada ano.
