### ISSUE TITLE
Atualizar ambiente de PROD da BAE

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1431]
- [x] Fazer o backup do servidor de produção de código
- [x] Fazer o backup do servidor de produção de dados
- [x] Fazer o backup dos storages do MySQL e do Elasticsearch
- [x] Fazer o versionamento da branch master da API
- [x] Fazer o versionamento da branch master da Front
- [x] Configurar o pipeline da API
- [x] Configurar o pipeline do Front
- [x] Configurar o pipeline do Site (Biblioteca)
- [x] Fazer o merge da branch API **master em development**
- [x] Fazer o merge da branch API **development em master**
- [x] Fazer o merge da branch Front **master em development**
- [x] Fazer o merge da branch Front **development em master**
- [x] Fazer o merge da branch Biblioteca **master em development**
- [x] Fazer o merge da branch Biblioteca **development em master**
- [x] Desativar a API - **php artisan down** 
- [x] Executar a migration na API
- [x] Rodar o script de Reordenação dos Grupos **- Servidor de dados**
- [ ] Rodar o script de Criação da cidade-estado **- Servidor de dados**
- [x] Apagar o índice children do elasticsearch
- [x] Criar o novo índice children do elasticsearch **(verificar novos campos no mapping - tree_id, group_id)**
- [x] Fazer reindexação do índice children

**Comment by manoelsouzaunicef** [comment]
**Fazer o versionamento da branch master da API**
https://github.com/UNICEF01/busca-ativa-escolar-api/releases/tag/v.3.4

 **Fazer o versionamento da branch master da Front**
https://github.com/UNICEF01/busca-ativa-escolar-web/releases/tag/v3.4
