### ISSUE TITLE
Dividir abas em respondidas e pendentes

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1448]

**Comment by manoelsouzaunicef** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1448?planning-poker) with Zenhub @ricardosreichert @manoelsouzaunicef

**Comment by ricardosreichert** [comment]
@manoelsouzaunicef Preciso que voce realize um QA com atenção nesse pull request, pois eu instalei o LINT e PRETTIER para limpar o codigo.

Para testar, tens que pegar as modificações no back.

https://github.com/UNICEF01/pesquisas_front/pull/3
