### ISSUE TITLE
BUG - Numero de Adesões no Dashboard nao corresponde com o valor real

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1453]
![image.png](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/779b97b3-39b0-47ef-855e-b5ed5a9e0aeb)

**Comment by manoelsouzaunicef** [comment]
Precisamos rever o script no servidor de produção. O cache não está atualizando
