### ISSUE TITLE
Identificar os usuários que possuem casos relacionados à responsabilidade no estado antigo.

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1465]

**Comment by manoelsouzaunicef** [comment]
Esses dados podem ser localizados apenas no Elasticsearch.
Query para agregações por estado:

CURL /children/child/_search 

`{
  "size": 0,
  "aggs": {
    "UF": {
      "terms": {
        "field": "assigned_uf"
      }
    }
  }
}`
