### ISSUE TITLE
Possível erro dashboard

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#148]
Alertas aprovados: 32
Casos em andamento: 31
Gráfico dos motivos: 2 alertas

**Comment by biancacambiaghi** [comment]
![image.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46e1999b2487c1e5cdf9ad4cae58f3806b1c65262b05a77a2086bb2dec157f515c5f4efe13580946f9fedb39baa47e21d40854b088270a36d43703adbf881eba04ba20834c86b3b48a4ec7fa70.png)

**Comment by biancacambiaghi** [comment]
Dúvidas:

1. A diferença entre os alertas e casos seria 1 caso cancelado? (já que alertas rejeitados está zerado)

2. O gráfico está mostrando apenas 2 alertas, seria um erro?

**Comment by sandyunicef** [comment]
#366 resolvido
