### ISSUE TITLE
Adicionar prazos padrão para gestão de casos (30 dias)

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1484]
- Definir prazo padrão de 30 dias para gestão de casos.
- Permitir personalizar prazo por caso durante criação. (MOVIDO PARA NOVO CARD)
- Enviar notificação próxima ao vencimento do prazo. (MOVIDO PARA NOVO CARD)

**Detalhes:**
Como Manoel citou, o establecimento de prazos foi uma decisão antiga, dos primeiros momentos de desenvolvimento da metodologia, em que se decidiu pela ausência de prazo em Gestão do Caso. Porém, os municípios apontaram que gostariam de pelo menos ter a possibilidade. Sugiro 30 dias de prazo default mas sem prazo obrigatório.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjM4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b1a2c505ba491dc789df54d2a749945958798c13/image.png)

**Comment by manoelsouzaunicef** [comment]
Precisamos criar um comando do laravel para atutlizar todos os settings já salvos com gestao_do_caso = 0 para gestao_do_caso = 30
