### ISSUE TITLE
Verificar rota get_via_token do processo de adesão. Está forçando o retorno de cidades erradas para o front que está em processo de configuração

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1496]

**Comment by manoelsouzaunicef** [comment]
Linha 189:

`		$cityId = $signup['original']['city_id'];
		$city = $signup->getCitybyId($cityId);
		$signup->setAttribute('city', $city);
`

O código acima não faz muito sentido. Verificar a necessidade dele no processo de adesão

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1496?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by manoelsouzaunicef** [comment]
Processo de adesão de cidades apresenta dados de outra adesão
Essa é a 2ª etapa. Logo após a confirmação da adesão feita pelo gestor nacional. A cidade é de Capim Grosso BA e está exibindo a primeira adesão de estado (que não tem ligação nenhuma com esse caso)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMi9oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a12592d631acbbf13cdf57fda472578475c6927f/adesao%20capim%20grosso%20ba.jpg)

**Comment by manoelsouzaunicef** [comment]
**Após correção da API**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM25oQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6b8e18c0090a924c13b15c016df44e260ff5d6a/correcao.jpg)
