### ISSUE TITLE
Permitir importação de dados do EducaCenso pelos Estados

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1498]
Permitir o uso da ferramenta de importação do Educa censo para os Estados

Tarefas:

- [x] Criar planilha padronizada para que os Estados possam importar os dados do EducaCenso.
- [x] Implementar opção na interface do sistema para que os usuários dos Estados possam realizar a importação.
- [x] Ajustar código da importação para vincular os dados importados ao município da escola referente e não ao município do usuário logado.

**Comment by manoelsouzaunicef** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1498?planning-poker) with Zenhub @ricardosreichert

**Comment by manoelsouzaunicef** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1498?planning-poker) with Zenhub @manoelsouzaunicef
