### ISSUE TITLE
Inserir opção de excluir estados que estejam preenchidos errado

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#15]

**Comment by manoelsouzaunicef** [comment]
O que seria excluir estado? O que pode existir de errado em cadastro de estado é o cadastro de um usuário. Essa edição/ desativação já é feita na lista de usuários. Uma alternativa de desativação de estado seria mais interessante. A cada estado desativado, seus usuários também serão desativados

**Comment by danielbarboni** [comment]
@manoelsouzaunicef  teste
