### ISSUE TITLE
Agrupar dados de atraso escolar por ano no gráfico do TSE

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1500]
Descrição:
- Agrupar as colunas do gráfico de atraso escolar, combinando os dados dos anos 1, 2 e 3 em uma única coluna por ano.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWFtQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--39225725bc67620ef68f3fcaa374617e725fa5a8/tse.jpg)

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1500?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by manoelsouzaunicef** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1500?planning-poker) with Zenhub @ricardosreichert

**Comment by manoelsouzaunicef** [comment]
Antes:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeExJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fab4b4be73e6e34da07ace3b583b0a186b48ea72/era_.jpg)

Depois (Somente ano 2021)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeFBJQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2b445a9dee5246f472c4b29c1271c5290a377bf/ficou.jpg)
