### ISSUE TITLE
Recuperar o acesso do perfil de coordenação estadual na tela de Relatórios

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1531]

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1531?planning-poker) with Zenhub @manoelsouzaunicef
