### ISSUE TITLE
Permitir o cadastro de rematrículas de pessoas com mais de 18 anos na etapa de pesquisas

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1532]

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1532?planning-poker) with Zenhub @manoelsouzaunicef
