### ISSUE TITLE
BAE - Corrigir metas do SELO que são exibidas no gráfico de evolução da Dashboard de gestores nacionais

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1544]
<img width="573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkRtQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--806e9b6482d0ae38305df74ebd8e501f9e4cd32c/image.png" alt="image.png" />

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1544?planning-poker) with Zenhub @manoelsouzaunicef
