### ISSUE TITLE
Sistema de pesquisas - Formulário de Comprovação da Lei 13.431/2017 no Selo UNICEF

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1546]
https://unicef-my.sharepoint.com/:w:/g/personal/hhebert_unicef_org/EX0I40dw3pJBkp8t-nJITNQBwxWKKZPlrfd2frHLW2wwEA?e=wTu8Zo&CID=447f01d9-f240-943d-f188-604038b7c580

Esse formulário segue o mesmo padrão de outros que já estamos utilizando, como do PMPI, Lavagem de Mãos e os de Educação.

**Comment by manoelsouzaunicef** [comment]
Finalizada:
https://pesquisas.unicef.org.br/pesquisa/34
