### ISSUE TITLE
Sistema de pesquisas - UAPI Saúde

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1547]
https://unicef.sharepoint.com/:w:/s/BRA/EfOuYFeAj5RCjzoBrpm2FIABDqlRPUUdltaDydzKtxURrw?e=TzwedH&CID=f88d181f-ed43-76dd-eedb-e05371934231

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1547?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by manoelsouzaunicef** [comment]
Aguardando aprovação
https://pesquisas.unicef.org.br/pesquisa/35
