### ISSUE TITLE
BAE - Antigo perfil estadual - Erro no carregamento dos mapas

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1566]
Dados do mapa com perfil estadual não está carregando os dados.

<img width="1250" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXVzQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0996d101bb581c321b13157d2d6aa2a1c9fb14e6/mapa.jpg" alt="mapa.jpg" />

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1566?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by manoelsouzaunicef** [comment]
Esse casos está mais confuso do que imaginávamos. A princípio o erro estava relacionado apenas ao fato dos estados não conseguirem analisar o metrics overview (quadro de status dos casos) dos municípios na sessão Mapa de Casos da Dashboard do antigo estado. O mesmo ocorria para o gestor nacional. Seguindo o fluxo de seleção do estado e município, encontramos diversos erros relacionados ao processo de geolocalização. 

O componente está dividido entre Mapa de casos e o quadro de casos (valores por status).

**Mantive o mapa** (ainda com falhas) para os perfis de cidades e **removi dos perfis de gestão nacional e estadual.** Está completamente impossível resolver a questão do mapa.

O overview dos status foi corrigido. Os valores corretos por status já estão sendo exibidos no perfil municipal, estadual (antigo perfil) e nacional.

<img width="1184" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK0lvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cd7c330c4ab78fb1b65f8aa10b9a1cc504c5283e/nmapa.png" alt="nmapa.png" />

Fluxo: Brasil -> Sergipe -> Itabaiana:

<img width="933" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1VvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bdb7769e5e32732af6f2aaf3e873fd69e3dbb335/mapa1.png" alt="mapa1.png" />
<img width="961" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1lvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f63662ff5faba4427e760d2dae4d2b90308d1d1/mapa2.png" alt="mapa2.png" />
<img width="939" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2NvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f363866ce2b750a8aedf9ed3c4a462ed96d4a20f/mapa3.png" alt="mapa3.png" />
