### ISSUE TITLE
BAE - Antigo perfil estadual - Cadastro de novos usuários para gestão dos casos

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1589]
**Descrição:** 
Não é possível cadastrar ninguém para a tarefa de acompanhar os municípios.
Verificar o processo de cadastro de usuários que precisam de grupos - também com perfil nacional

**Comment by manoelsouzaunicef** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1589?planning-poker) with Zenhub @ricardosreichert

**Comment by manoelsouzaunicef** [comment]
**Fazer o reindex de todos os casos** ⚠️
