### ISSUE TITLE
TSE - Explicação legendas dos Gráficos de Aprendizagem

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1607]

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1607?planning-poker) with Zenhub @manoelsouzaunicef
