### ISSUE TITLE
Correção de consulta de Nome no ElasticSearch

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1623]
<img width="989" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1NwQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6bacb9c74c5245c2baff243de41dad44adaf124d/image.png" alt="image.png" />

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1623?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by manoelsouzaunicef** [comment]
Verificar se basta mudar a configuração do tipo de busca que está sendo feita aqui:

https://github.com/UNICEF01/busca-ativa-escolar-api/blob/master/app/Http/Controllers/Resources/ChildrenController.php#L77

Verificar **addTextFields**
