### ISSUE TITLE
TSE - Remover casas decimais dos gráficos do Painel de Aprendizagem

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1628]
Remover casas decimais dos gráficos do Painel de Aprendizagem
Padronizar altura do gáfico de Proficiência média para todos os tipos de seleção possível.

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1628?planning-poker) with Zenhub @manoelsouzaunicef
