### ISSUE TITLE
TSE - Recuperar post customizado do tipo Materiais

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1631]
O post do tipo Experiência didática não está carregando os links dos documentos do tipo Materiais.
Materiais deveria ser outro tipo de conteúdo customizado, poém não foi importado, logo todos os campos dos posts das experiências estão aparecendo em branco.

Fazer edição do template abaixo exibindo os subtítulos apenas quando houver o conteúdo relacionado
Corrigir o termo objetivo digital para objeto digital.

<img width="787" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0s0QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6fd87c623a8476acc180f695fc62be6c96d206f9/materiais.png" alt="materiais.png" />

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1631?planning-poker) with Zenhub @manoelsouzaunicef
