### ISSUE TITLE
BAE - Limitar intervalo de tempo de busca de dados no Elasticsearch no ChildrenDaily

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1638]

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1638?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by manoelsouzaunicef** [comment]
<img width="883" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBejBBQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b471f12943d87e282875def1bb619e4e529919c3/limitetempo.png" alt="limitetempo.png" />

O payload do front limita o resultado em 6 meses evitanto que a API faça o filtro de todos os dados do Elasticsearch.
