### ISSUE TITLE
BAE - Verificar filtro do responsável pelo caso

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#1645]
<img width="838" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOVFpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bf20dbc10a773ccbfe6b97bdbcac3ec48f04fadd/image.png" alt="image.png" />

<img width="969" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUlpQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c91b41414461de802f43694f2b509343bdb9b5eb/image.png" alt="image.png" />

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/1645?planning-poker) with Zenhub @manoelsouzaunicef

**Comment by ricardosreichert** [comment]
Adjust filtering logic and update total results in search response

- Normalize assigned_user_name to lowercase and ASCII before filtering
- Ensure proper filtering of search results based on assigned_user_name
- Update total results count after filtering
