### ISSUE TITLE
Grupo obrigatório "educação" - impedir edição

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#165]
Notei que está sendo permitida a edição do nome do grupo SECRETARIA MUNICIPAL DE EDUCAÇÃO, obrigatório para todos os município. Gentileza impedir edição...

Ao menos um município, por erro, acabou editando o título e exclui o grupo EDUCAÇÃO.

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/53664849-877def00-3c48-11e9-9e78-d2851c7ac571.png)

**Comment by manoelsouzaunicef** [comment]
Já trabalhamos com a questão da obrigatoriedade desse campo, mas não com a impossibilidade de editar. Deixaremos como uma melhoria

**Comment by manoelsouzaunicef** [comment]
Nova reorganização dos grupos impede esse processo de edição.
