### ISSUE TITLE
Alerta de Casos Sem Responsável no Painel da Home Após Readesão

### ISSUE THREAD

**Issue by ricardosreichert** [UNICEF01/BuscaAtiva#1685]
Após a finalização do processo de _readesão_, adicionar um alerta no painel da home informando o usuário de que existem casos sem um responsável atribuído. O alerta deve:

- Exibir o número total de casos sem responsável.
- Incluir um botão que redireciona o usuário para a listagem desses casos sem responsável.

<img width="1199" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjhYQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7992cd9cec5fa4d7c702e8da85d3d45cec691a39/image.png" alt="image.png" />

**Comment by manoelsouzaunicef** [comment]
**Solução**

<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXFCQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--527a02ce45711c1db5b15458c5f2b795caad3d38/Untitled.jpg" alt="Untitled.jpg" />
