### ISSUE TITLE
Inclusão de BAIRRO no painel e casos

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#171]

**Comment by biancacambiaghi** [comment]
Solicitação dos municípios de inclusão de uma coluna BAIRRO nas lista de casos que aparece nas abas PAINEL e CASOS. 

Apesar de ser uma variável que não é padrão (vem de uma campo aberto) achamos uma informação relevante para ficar evidente. O que acham?

**Comment by biancacambiaghi** [comment]
![bairro.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46ea959331908cebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98515be04bf23894882bebd824ec1e92f68.jpg)

**Comment by sandyunicef** [comment]
Resolvido na issue #182
