### ISSUE TITLE
Diferença entre números Dashboard e Relatórios

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#172]

**Comment by biancacambiaghi** [comment]
Nova Iguaçu / Dashboard: 0 casos

**Comment by biancacambiaghi** [comment]
![novai1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46e69b8c228bd2ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98a15be04bf2389488db4ba8d4ec5ed2f68.jpg)

**Comment by biancacambiaghi** [comment]
Nova Iguaçu / Relatórios: 1 caso

**Comment by biancacambiaghi** [comment]
![novai2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46e69b8c228bd1ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98a15be04bf2389488db4b58b4dc2ed2f68.jpg)

**Comment by biancacambiaghi** [comment]
Queimados / Dashobard: 70 casos em andamento

**Comment by biancacambiaghi** [comment]
![queimados11.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46f9819f2a8f82ad80faee12e611b2843b492d762a10e17132d0e129bb132b02570a4dab15585c44fcabdb2bf0b43977d84e17ff933c0120996048e6edc00db513bb28814e80b3bf884bc8ec3d22e58a8a5d73.jpg)

**Comment by biancacambiaghi** [comment]
Queimados / Relatórios: 69 casos

**Comment by biancacambiaghi** [comment]
![queimados1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46f9819f2a8f82ad80faee01e81fe086264c22703d46f9692587e22cee1278590a5c49f8415b5f44aeab897da4b33b22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a80b5be8d44c4eb3c26e48d9d02.jpg)

**Comment by biancacambiaghi** [comment]
Rio Bonito / Dashboard:  186 casos + 1 matrícula

**Comment by biancacambiaghi** [comment]
![riobonito1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46fa9d95218d8da09be6ee01e81fe086264c22703d46f9692587e22cee1278590a5c49f8415b5f44aeab897da4b33b22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a80b5be8d44c6e13d21e18f9d02.jpg)

**Comment by biancacambiaghi** [comment]
Rio Bonito / Relatórios: 182 casos + 1 matrícula

**Comment by biancacambiaghi** [comment]
![riobonito2.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46fa9d95218d8da09be6ed01e81fe086264c22703d46f9692587e22cee1278590a5c49f8415b5f44aeab897da4b33b22984019af80330b2b9b645bf9fa9015ad00b22a8a4a80b5be8d44c7ea3f26e78f9d02.jpg)

**Comment by biancacambiaghi** [comment]
Pirai / Dashboard: 47 casos + 27 matrículas

**Comment by biancacambiaghi** [comment]
![Slide1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d2ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98a15be04bf258d4f87b0bc8e45c9ee2f68.JPG)

**Comment by biancacambiaghi** [comment]
Pirai / Relatórios: 27 casos + 19 matrículas

**Comment by biancacambiaghi** [comment]
![Slide2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d1ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98a15be04bf258d4f87b0be8344c0ed2f68.JPG)

**Comment by biancacambiaghi** [comment]
Na verdade esse último exemplo (PIRAI) está correto, mas a ordem de aparição dos dados do gráfico é que se inverteram e eu olhei errado. Podem desconsiderar.

**Comment by sandyunicef** [comment]
Ok

**Comment by biancacambiaghi** [comment]
Sandy, era para desconsiderar só o último exemplo, não a issue toda.
Há sim uma diferença entre os nºs do dashboard e relatórios.

**Comment by sandyunicef** [comment]
ok


Sandy Santos
IT Consultant

UNICEF Brasil

Tel: + (55 61) 3035-1960 | 98366-1622, E-mail: ssantos@unicef.org



United Nations Children's Fund
SEPN 510, Bloco A, 2º andar, Brasília, DF, Brazil
Follow us on Facebook<http://www.facebook.com/UNICEFBrasil>, Twitter<http://www.twitter.com/unicefbrasil>, Instagram<http://www.instagram.com/unicefbrasil>, YouTube<http://www.youtube.com/unicefbrasil> and at www.unicef.org.br<http://www.unicef.org.br/>


[cid:6b5229f3-2b32-4a26-b2f7-526d5deeab68]

________________________________
De: biancacambiaghi <notifications@github.com>
Enviado: terça-feira, 28 de maio de 2019 10:56
Para: UNICEF01/BuscaAtiva
Cc: Sandy Santos; State change
Assunto: Re: [UNICEF01/BuscaAtiva] Diferença entre números Dashboard e Relatórios (#172)


Sandy, era para desconsiderar só o último exemplo, não a issue toda.
Há sim uma diferença entre os nºs do dashboard e relatórios.

**Comment by sandyunicef** [comment]
Certo


Sandy Santos
IT Consultant

UNICEF Brasil

Tel: + (55 61) 3035-1960 | 98366-1622, E-mail: ssantos@unicef.org



United Nations Children's Fund
SEPN 510, Bloco A, 2º andar, Brasília, DF, Brazil
Follow us on Facebook<http://www.facebook.com/UNICEFBrasil>, Twitter<http://www.twitter.com/unicefbrasil>, Instagram<http://www.instagram.com/unicefbrasil>, YouTube<http://www.youtube.com/unicefbrasil> and at www.unicef.org.br<http://www.unicef.org.br/>


[cid:b5488e7a-9de0-4cb5-8d7f-1d289e03df17]

________________________________
De: biancacambiaghi <notifications@github.com>
Enviado: terça-feira, 28 de maio de 2019 10:56
Para: UNICEF01/BuscaAtiva
Cc: Sandy Santos; State change
Assunto: Re: [UNICEF01/BuscaAtiva] Diferença entre números Dashboard e Relatórios (#172)


Sandy, era para desconsiderar só o último exemplo, não a issue toda.
Há sim uma diferença entre os nºs do dashboard e relatórios.
