### ISSUE TITLE
Contagem Dashboard casos cancelados

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#173]

**Comment by biancacambiaghi** [comment]
Queria confirmar se a diferença entre os números do município exemplo se refere a CASOS cancelados (não alertas) e se sim, sugerir que no dashboard esse número também seja incluído para facilitar a leitura e análise dos números. Os dados são públicos e podem gerar muitas dúvidas para pessoas que não usam a plataforma e estão habituadas com as etapas, status e possibilidades da plataforma.

**Comment by biancacambiaghi** [comment]
![itaguai.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46e1809b249782a0cda5fd53b652fa912a5265296b51a12a74d4b32be74728560b5f4dac410a0d44aafb8c2cf4a42062c80d55b98e30063e937f03a6aa8317b500bf25884d82beb58944c8e13b37aa.jpg)

**Comment by biancacambiaghi** [comment]
ALERTAS: 
123 aprovados (ou seja, viraram casos)
+ 1 pendente
+ 1292 rejeitados
= Ou seja, esse município já fez 1416 alertas (soma dos 3 números)

CASOS:
55 em andamento  --> entendo então que há 68 casos (123 alertas aprovados - 55) que foram cancelados, é isso?? Se sim, sugestão de incluir essa informação no dashboard. 
+ 7 (re)matrícula (casos que estão na etapa de (re)matrícula + na etapa de observação)
= Ou seja, esse município está fazendo a gestão de 62 casos

****** OBS: Se os 7 casos de (re)matrícula estão DENTRO dos 55 casos em andamento, sugiro muito rever essa contagem ou a forma de disposição dos dados. Porque a disposição dos números lado a lado sugere que estão no mesmo nível e ambos compõem o total de casos (assim como ocorre nos alertas).

**Comment by manoelsouzaunicef** [comment]
Entendemos o que está ocorrendo. Deixaremos na fila para as melhorias.
