### ISSUE TITLE
Diferença gráficos motivos Painel x Relatórios

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#175]

**Comment by biancacambiaghi** [comment]
painel

**Comment by biancacambiaghi** [comment]
![graficopianel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46ef869b258b80a69fe0be4da151b2d86b56357c2301a03f32dfa17dbd437f505f0c46f9425f0b44fff98979f4b66a728f5b59ffcd7f1d2598694ef1e1c84afd13b0328a478fb7b98f4fc2e03d22e08386493f0c48.jpg)

**Comment by biancacambiaghi** [comment]
relatórios

**Comment by biancacambiaghi** [comment]
![graficorelatorio.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46ef869b258b80a69decb342b052e29d26046b313916ac217586f76ae5002e030e0b4fac12500a47fbad8928a6b66e228a0a09e8d63f4d68d47f40f2ecdd42e64bef62994597b7b4804dc5ed3e27ef8b874f3f1605189bb2.jpg)

**Comment by biancacambiaghi** [comment]
O número certo de casos é 52, conforme gráfico geral da aba de relatórios:

**Comment by biancacambiaghi** [comment]
![geralrel.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46ef9188228e91ac83abf301b44fff9e2c4533317346f6297181b278bc1a7e52580b4eaf41580d16fcaf8b2ea1e42e6c981e5ab38532022d8c6853beb2901eb80bbb258e4c87bebc834ec7ee3e2cf5c6.jpg)

**Comment by danielbarboni** [comment]
Corrigir no Painel o gráfico de Casos pois os dados que estão sendo apresentados não é dos Casos e sim dos Alertas.

Aba Relatorios:

![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/edebf6a1-2cbd-4393-b714-a5eec53b3677)

Aba Painel:

![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/c91158cf-9f5e-4a24-a797-259e23081073)
