### ISSUE TITLE
Aceite de alertas pendentes em bloco

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#181]

**Comment by biancacambiaghi** [comment]
Criar algum mecanismo de aceite de alertas em bloco para casos de município com muitos alertas e que fizeram importação do Educacenso e/ou futuramente de planilhas próprias. 

Algo parecido com seleção de emails (selecionar todos da página). Objetivo é otimizar o tempo de aceite de alertas que já foram verificados antes da importação.

**Comment by sandyunicef** [comment]
Vamos propor uma solução disponibilizando um botão de aceitação ou rejeição em cada linha.

**Comment by biancacambiaghi** [comment]
O que acham de colocar também um botão para visualizar o alerta? Igual o "lápis" na aba de casos. Hoje você visualiza o alerta clicando na linha dele, mas não sei se isso é tão óbvio para todo mundo. E colocando os botões aceitar/rejeitar em cada linha pode induzir a pessoa a não conferir as informações do alerta antes de aceitar. É o que queremos com o aceite em bloco, mas não para todos os alertas.
