### ISSUE TITLE
problema na organização alfabética da lista

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#190]
ambiente oficial
usuários
uf/município

no caso de PE o município de Águas Belas está no final da lista. isso dificulta encontrá-lo

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/55570690-4448ed00-56da-11e9-80f2-2dce021ecdd5.png)

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/190?planning-poker) with Zenhub @manoelsouzaunicef
