### ISSUE TITLE
Indicação de questões obrigatórias nos formulários PDF offline

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#201]
Sugestão de em todos os formulários offline (de todas as etapas) haver indicação com * dos campos que são obrigatórios na plataforma. 

Isso facilita muito o trabalho de municípios que não possuem internet ou dispositivos móveis no campo e estão usando os formulários impressos. Assim fica explícito quais são as informações obrigatórias a serem coletadas e facilita depois o trabalho de inserção dos dados na plataforma e de avanço das etapas.

**Comment by sandyunicef** [comment]
@Vilmar72
