### ISSUE TITLE
visualização das Direcs / regionais pelos municípios

### ISSUE THREAD

**Issue by daniellarocha** [UNICEF01/BuscaAtiva#212]

**Comment by daniellarocha** [comment]
Os municípios hoje podem visualizar todas as Diretorias / Regionais / Coordenações estaduais que o seu estado cadastrar. Porém, cada município é ligado a somente uma Diretoria. Assim, o ideal seria ele visualizar, na hora de atribuir os casos, apenas os usuários da sua Direc. não sei se é possível criar um filtro para isso, evitando-se, assim, uma extensa lista de usuários para que possa atribuir um caso.

**Comment by sandyunicef** [comment]
De acordo com o que a gente conversou, é possível filtrar as diretorias na hora da atribuição @daniunicef
