### ISSUE TITLE
Visualização nas abas do coordenador estadual

### ISSUE THREAD

**Issue by daniellarocha** [UNICEF01/BuscaAtiva#213]

**Comment by daniellarocha** [comment]
O coordenador estadual não tem a aba casos para que possa acompanhar o trabalho dos supervisores estaduais, saber que casos foram atribuídos para cada supervisor, os prazos etc. É importante ele poder fazer a gestão disso (assim como o coordenador operacional faz).

**Comment by sandyunicef** [comment]
Vai ser resolvida na issue #131
