### ISSUE TITLE
Perfil dos supervisores autoriza preencher etapas que ele não pode

### ISSUE THREAD

**Issue by daniellarocha** [UNICEF01/BuscaAtiva#214]

**Comment by daniellarocha** [comment]
O supervisor estadual visualiza casos ainda nas etapas de pesquisa e análise técnica, mas não deveria, pois os casos, quando chegam para ele, são apenas na etapa de rematrícula. Então ele só deve visualizar os casos a ele atribuído, o que vai ser sempre na etapa de rematrícula. Ele também pode preencher as informações na pesquisa, análise etc - mas igualmente não pode fazer isso, pois é atribuição apenas do município. Precisa bloquear as etapas de alerta, pesquisa e análise técnica para ele, tanto de visualizar como de preencher infos.

**Comment by sandyunicef** [comment]
Vai ser resolvida na issue #234
