### ISSUE TITLE
Mensagem de erro ao cadastrar usuários

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#221]
Temos recebido muitas reclamações de erro no cadastro de usuários.
Assunto já foi debatido no wpp e isso acontece, tudo leva a crer, quando tenta-se cadastrar uma pessoa já cadastrada.

Problema que a mensagem de erro apenas diz que ocorreu um erro... o ideal seria "usuário já cadastrado"

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/57327358-27db0e80-70e5-11e9-939c-bc927d9a2411.png)

**Comment by biancacambiaghi** [comment]
Os casos que tive contato não eram usuários cadastrados, eram novos mesmo. E apesar de mostrar a mensagem de erro, o cadastro do usuário era feito mesmo assim.
