### ISSUE TITLE
Marcação dos motivos entre etapas

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#227]

**Comment by biancacambiaghi** [comment]
Caso está na etapa de pesquisa.
O motivo indicado no alerta é "FALTA DE TRANSPORTE ESCOLAR"

**Comment by biancacambiaghi** [comment]
![Slide1.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d2ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98515be04bf278f468cb4bf8e4fc3ee2f68.JPG)

**Comment by biancacambiaghi** [comment]
Como é um motivo com "sub-motivos", quando vai para etapa de pesquisa automaticamente os sub-motivos são marcados.

**Comment by biancacambiaghi** [comment]
![Slide2.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d1ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98b15be04bf278f468cb4b48e4bc5ef2f68.JPG)

**Comment by biancacambiaghi** [comment]
Na realização da etapa de pesquisa um dos sub-motivos é desmarcado, pois não se aplica.

**Comment by biancacambiaghi** [comment]
![Slide3.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d0ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98a15be04bf278f468cb5be8c4ec1e82f68.JPG)

**Comment by biancacambiaghi** [comment]
Mas quando salva e finaliza a pesquisa, na etapa de análise técnica, os dois sub-motivos aparecem (vagas e escolas) marcados novamente.

**Comment by biancacambiaghi** [comment]
![Slide4.JPG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46db98932787d7ebc3abaf51ab57f5973d047d317c06a22f21d5e070ba112c055f5c4eac130a5f12fefc8e79b4aa2e32db025fb28c341521842f1bbeb98b15be04bf278f468cb2bf8c4dc0ed2f68.JPG)

**Comment by biancacambiaghi** [comment]
Na verdade entendi o que acontece... Os motivos indicados na análise técnica são os marcados no alerta, mas como o motivo selecionado no alerta é um que possui sub-motivos, o sistema mostra como se os 2 sub-motivos tivessem sido selecionados. Quando na verdade o motivo selecionado foi outro, o mais geral. E aí falta a indicação de qual motivo foi marcado na pesquisa, como acontece em outras situações (abaixo).

Acho que uma solução seria alterar a indicação de qual motivo foi marcado no alerta (indicar o motivo geral e não os sub-motivos) ou então incluir o motivo (mesmo que repetido) que foi marcado na pesquisa.

**Comment by biancacambiaghi** [comment]
![Apresentação1.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46c98488269186a79be81c84079effc56b0a65633b0ba92e7391a172fd1779000b5e4eff490d5c43a8f98a2ba6e46e70dc5e0eea837f4366846c4ff8e7df46f554f832815d84beb68b49c5ef392cee8c884e361c020ac4.jpg)

**Comment by sandyunicef** [comment]
Feito

**Comment by biancacambiaghi** [comment]
Sandy, de fato agora a marcação dos motivos está correta. Mas vi que agora aparece uma mensagem em box azul que indica qual foi o motivo marcado no Alerta. Desculpa porque pode ser muito preciosismo meu, mas uma faixa de texto de outra cor me remete à uma mensagem/lembrete do sistema e não de fato uma informação que pertence àquele campo. Ela fica destacada das outras sendo que nem sempre precisa ter esse destaque. O motivo marcado na alerta por exemplo pode ser outro completamente diferente da etapa de pesquisa. Por outro lado, apesar de estar destacada ela não induz o leitor a ler justamente porque dá a impressão de ser uma mensagem do sistema... Não sei, fiquei confusa, pode ser porque já estava habituada também... Tive a sensação que a disposição de antes (motivos listados um abaixo do outro e com a indicação de qual era da etapa de alerta (com um label cinza antes da frase) indicava melhor a informação. Não sei se os outros concordam...
