### ISSUE TITLE
Disparidade na contagem de casos 

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#228]
Horizonte/ CE relata diferença na contagem do casos criados a partir do Educacenso. Constam 297 casos, mas somente 128 registros. 

![image.png](https://images.zenhubusercontent.com/5ce2b527b3839c6356b066ab/e3b61863-45ab-46b8-85f0-13796004b794)

![image.png](https://images.zenhubusercontent.com/5ce2b527b3839c6356b066ab/cc6de16d-7fa6-4b89-b6d3-9b685c570466)

**Comment by manoelsouzaunicef** [comment]
Criamos uma solução para este problema. Outros usuários relataram esse detalhe. Criaremos uma nova issue para paginação dos dados provenientes do Elasticsearch.
