### ISSUE TITLE
Definir usuários com permissão de acesso às funcionalidades EDUCACENSO e ESCOLAS

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#230]
Somente coordenador operacional e supervisor institucional da educação devem ter permissão para acessar as abas do Educacenso (importação dentro da aba Configurações) e das Escolas.

**Comment by manoelsouzaunicef** [comment]
Essa questão já foi resolvida.

Coordenador operacional:
![coordenador_op.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/6d16f464-54e2-4709-bb0d-a39d791e2ba1)

Coordenador operacional da educacao:
![coordenador_op_edu.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/4a966363-8266-42bf-bd89-32917cf0799c)

Supervisor institucional:
![supervisor_op.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/4f90ffed-4e72-423c-9231-16d1dcd2ed03)

Supervisor institucional da educacao do grupo Secretaria Municipal de Educacao:
![supervisor_op_educacao.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/4d1e9d6e-67be-4822-899c-6dd8abec4319)
