### ISSUE TITLE
Bloquear temporariamente a importação de novos dados do INEP e limpar a fila de importação de dados do INEP da plataforma de produção. Subir as modificações relacionadas ao task #3 para produção e liberar novamente a importação de novos dados do INEP após isto.

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#27]

**Comment by manoelsouzaunicef** [comment]
Limpei a fila de processos
Aguardando a sugestão do Vilmar e da Dani para os textos de alerta que aparecem na tela do upload.
 
![Screen Shot 2018-10-16 at 16.27.33.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236455f56b7191a379e90c2956415c4dbe5d4a1f06a3a3dc78e2a436628f0e5ab9d06d0c7c933e16f8b8811fbf53e820dd4d80b1ee9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecb51f14ae9455cac153063f43b.png)
