### ISSUE TITLE
Nova funcionalidade p/ impressão do histórico de um caso

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#271]
Sugestão de alguns municípios que acompanhamos da plataforma permitir a geração de um "relatório / arquivo pdf" com todo o histórico (todas as etapas percorridas e suas respectivas informações) de um caso.

Alguns municípios estão tendo a necessidade de extrair da plataforma uma "comprovação" de que o caso está sendo acompanhado e precisam imprimir / ter um arquivo digital para anexar em outros processos internos.

**Comment by danielbarboni** [comment]
Em reunião no dia 03/12/2019, envolvendo Sidney e Daniella foi definido que esta issue não é mais necessária.
