### ISSUE TITLE
Painel 30 dias do Gestor Politico em Branco

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#29]
No painel do Gestor Político o primeiro item ‘Evolução do Busca Ativa Escolar (30 dias)’ está sempre em branco (só temos acesso à plataforma teste).

**Comment by danielbarboni** [comment]
![BAE_1.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bad106c499b870012b500ed/125516c66e82c728ace21e0d46cab5bf1cd3c1e5cdf9ad4cae58f3806b1c65262b05a77a2086bb2dec157f515c5f4efe13580946f9fedb39baa47e21d40854b088270a36d43703adb1881eba05b8218a4b86b0bf834dc0fa70.PNG)

**Comment by sandyunicef** [comment]
Foi verificado que o histórico é criado pelo command DailyMetric o qual e executado uma vez por dia, devido a grande quantidade de casos o rotina nao estava funcionando corretamente. O chunk divide a execucao dos resultados de forma a não sobrecarregar o sistema.
