### ISSUE TITLE
Limpar os casos da base de dados de testes

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#31]
Objetivo de zerar o ambiente de testes para recomeçar a criação de casos e testes.

**Comment by manoelsouzaunicef** [comment]
Encaminhei email para a equipe que faz as formações para saber se iremos limpar  a base de testes

**Comment by danielbarboni** [comment]
Não iremos limpar a base.

**Comment by manoelsouzaunicef** [comment]
Equipe de gestão concordou em manter os casos em andamento no ambiente de testes
