### ISSUE TITLE
Exibir o painel de status também para gestores nacionais e estados

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#332]

**Comment by manoelsouzaunicef** [comment]
![Screen Shot 2019-09-30 at 09.56.28.png](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/6b0dfd0b-dc23-465e-996b-63dee8cd5184)

**Comment by sidneyvasconcelos** [comment]
Tal qual issue #333
