### ISSUE TITLE
Painel com status dos municípios

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#333]
Analisar com a equipe se é interessante desenvolver um painel onde o usuário em nível estadual e nacional possam ver o status de um município específico. A ideia é usar o mesmo painel da meta do SELO que está na tela de cada município. A equipe de gestão não decidiu se isso é interessante pois a dashboard pública tem todos esses dados em nível nacional, regional e estadual

**Comment by manoelsouzaunicef** [comment]
![Screen Shot 2019-09-30 at 09.56.28.png](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/b8fd85a2-4f84-4aa8-b2d8-9c810c2013d0)

**Comment by sidneyvasconcelos** [comment]
A funcionalidade de ver os painéis deve estar disposta para:

1- Perfis estaduais (para que selecionem o município que desejam visualizar)
- gestor estadual
- coordenador estadual
- supervisor estadual

2- Perfis nacionais (pata que selecionem UF e município que desejam visualizar)
- gestor nacional

Pergunto a vcs: qual destes perfis seria indicado para disponibilização aos parceiros implementadores nos estados? lembro-lhes de que para cada estado há uma equipe de uma ONG parceira que presta suporte aos municípios do Selo UNICEF; seria interessante darmos a essas equipes a oportunidade de ter a visão dos municípios dos seus respectivos estados.

**Comment by manoelsouzaunicef** [comment]
Issue fechada pois o painel publico já tem as informações
