### ISSUE TITLE
Avaliar solução para que na página dos municípios apareca os Gestor político e Coordenador operacional atualizados

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#34]

**Comment by biancacambiaghi** [comment]
A issue 76 (criei sem ver a 34) se refere à mesma questão, porém para o perfil do gestor nacional (para ele visualizar sempre os dados atualizados).

**Comment by manoelsouzaunicef** [comment]
Na reunião realizada no dia 10 de dezembro decidimos deixar apenas as informações essenciais relacionadas ao próprio município nessa tela. Foi decidido que apenas os usuários ativos devem aparecer na lista. O arquivo exportado deve refletir o mesmo.
