### ISSUE TITLE
Popup do curso BAE

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#345]
Criar o popup do curso do BAE.

**Comment by danielbarboni** [comment]
A Daniella Rocha ficou de repasar o conteúdo do popup (imagem, texto). Uma vez recebido isto, prosseguiremos com a criação do Popup.

**Comment by sandyunicef** [comment]
Bom dia Daniel e demais,

 

Segue abaixo as orientações para a entrada do pop up no site da BAe, a fim de divulgar o EAD, que será lançado na próxima quarta-feira (23 outubro):

 

Texto:

A Busca Ativa Escolar agora conta com um curso a distância para apoiar os municípios na sua implementação. Trata-se do Busca Ativa Escolar Na Prática, um curso autoformativo, dividido em módulos, de acordo com as funções desempenhadas por cada ator na estratégia e que podem ser trilhados a qualquer tempo. O curso possui certificação e está aberto na plataforma Google Sala de Aula.

 

Arte:

Usar a logo da BAE como referência de fonte e de cor azul

 

É algo bem simples e que inclusive vai ficar no site por período provisório. Neste momento servirá apenas para reforçar a divulgação.

 

 

Abç

 

 

Daniella Rocha

Education Consultant
