### ISSUE TITLE
Retirar a palavra agora do texto que aparece quando se clica em mais informações dos casos de andamento (Painel) e corrigir a palavra Plataforma no item  crianças ou adolescentes rematriculados

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#35]

**Comment by manoelsouzaunicef** [comment]
Aguardando mais detalhes de onde aparecem tais informacoes. Ja entrei em contato com Vilmar e Dani

**Comment by manoelsouzaunicef** [comment]
Depois de uma troca de emails com o Vilmar e Dani, foram sugeridos alguns acréscimos na mesma tela onde aparecem os termos. Vilmar e Dani sugeriram um novo quadro com o número de casos em atraso para o estado. Isso requer uma consulta um pouco mais complexa. Precisarei de um tempo a mais para criar. Sugeri para ambos deixar isso para a próxima sprint. Aguardando resposta.
