### ISSUE TITLE
Remover dos totais abaixo os casos cancelados, interrompidos e concluídos.

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#358]
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/c17c69ed-ac4c-4fc1-8f29-708892b36591)

**Comment by sandyunicef** [comment]
![image.png](https://images.zenhubusercontent.com/5cd96f8fee941c07853fb447/e3cf583a-7582-463a-96ff-8153e340f4a4)

Mudar informação exibidas nesse painel
