### ISSUE TITLE
Numero do NIS desaparece entre criação do alerta e pesquisa do caso

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#36]

**Comment by danielbarboni** [comment]
![Buscaativa1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bad106c499b870012b500ed/125516c66e82c728ace21e0d46ca8189208382bd86ffbe12e611b2843b492d762a10e17132d0e129bb132b02570a4dab15585c44fcabdb2bf0b43977d84e17ff933c0120996048e6edc00db513bb27814e80b2bd8b4cc4ea3523e6898b5d73.png)

**Comment by danielbarboni** [comment]
![Busca Ativa2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bad106c499b870012b500ed/125516c66e82c728ace21e0d46ca81892083c3889be0a942f61fbcd6395428792c07b7692ac7b62abe462a510c571baf460c5f47fcf9db79a6e03e758d0e19f1c32f0e2a92624cf5f2d75dad0ba821824584b3b88b4dc0ec3923e5888d462c53.PNG)

**Comment by biancacambiaghi** [comment]
Algo similar está ocorrendo com: nome da mãe, nome do pai, RG da mãe, RG do pai, telefone da mãe e telefone do pai. Esses campos aparecem na etapa de Alerta e são diferentes na etapa de Pesquisa. Então se todos forem preenchidos na etapa de Alerta, serão perdido quando migram para etapa da Pesquisa.
