### ISSUE TITLE
Validar e-mails na Landing Page

### ISSUE THREAD

**Issue by V1ctor1a** [UNICEF01/BuscaAtiva#381]
Estão chegando muitas mensagens de spam na caixa de entrada, acredito que por este motivo não tenho recebido contatos via site desde o início da semana.

**Comment by manoelsouzaunicef** [comment]
Emails não estão sendo encaminhados para o contato@buscaativaescolar.org.br

**Comment by manoelsouzaunicef** [comment]
Plataforma estava recebendo muitos spans e email de contato estava bloqueado para recebimento de mensagens
