### ISSUE TITLE
Erro ao salvar endereço nos casos

### ISSUE THREAD

**Issue by V1ctor1a** [UNICEF01/BuscaAtiva#382]
Ao salvar a etapa a plataforma informa que o caso não aparecerá no mapa. Corrigir os casos que já passaram desta etapa sem endereço identificado pelo Google.

**Comment by danielbarboni** [comment]
Implementar busca por endereços na API do google, utilizando algumas informações já conhecidas para melhorar a busca, como país, estado, cidade, etc.

**Comment by manoelsouzaunicef** [comment]
A API da Busca Ativa Escolar já tinha alguns parâmetros específicos para a busca de endereços, porém a String deveria ser encaminhada com os campos (Endereco,Numero,Bairro,Cidade) separados por vírgulas e nomes compostos unidos com um sinal de + (ex: Avenida+das+Nações). Seguimos a documentação fornecida pelo Google Geocoding https://developers.google.com/maps/documentation/geocoding/intro
