### ISSUE TITLE
REJEIÇÃO DE ALERTAS. No painel do agente comunitário um alerta rejeitado aparece como “em andamento” e não “rejeitado”. Alterar termos.

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#40]

**Comment by manoelsouzaunicef** [comment]
O front-end usava o campo do deadline para determinar o label do alerta. Mesmo com o caso rejeitado, ele exibia o termo em andamento, pois considerava o prazo para a etapa de alerta como a regra. Acrescentei um campo para o prazo mantive o outro para status.

**Comment by manoelsouzaunicef** [comment]
![Screen Shot 2018-10-31 at 16.46.30.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76236457f26b7191a379e90c2f57415c4ebe5d4a1f06a3a3dc78e2a436628f0e5ab9d06d0c7c933e16f8b8811fbf53e820dd4d80b1ee9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc59f64ae44e50a6143363f43b.png)
