### ISSUE TITLE
Aba usuários: problema com visualização de paginação e número de linhas

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#45]
No caso de várias páginas com registro de usuários, ao mudar o limite de exibição para 128 quando se está na página 3, por exemplo, fica tudo em branco. O ideal é as 128 linhas aparecessem na tela...

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/47232629-90130e80-d3a6-11e8-8f23-b0aaf745f593.png)

**Comment by manoelsouzaunicef** [comment]
Bug corrigido.
