### ISSUE TITLE
Ajustes de nomeclatura

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#455]
Implementação dos ajustes de nomenclatura e categorias da aba relatórios, conforme documento orientador já enviado;
Taxonomia

**Comment by manoelsouzaunicef** [comment]
Ajustes da plataforma Busca Ativa Escolar

No Painel externo
- Deve refletir a nova Dimensão: Status do caso (com suas 5 situações e novas nomenclaturas), conforme explicado abaixo
- Pausar consulta do estado até ajustar os dados (URGENTE)


Na aba Relatórios

1. Dimensão
- Status da criança: muda de nomenclatura para Status do Caso. Agora passa a ser composto pelas seguintes situações, também com novas nomenclaturas, que devem entrar com o texto completo (pode ser legenda, ou caixa de texto etc.)
                - Fora da escola: passa a se chamar – Caso em andamento: de pesquisa até (re)matrícula
                - Cancelado: passa a se chamar – Caso cancelado: em qualquer etapa do processo
                - Em observação: passa a se chamar – Dentro da escola e em observação: de 1ª a 4ª observação
                - Dentro da escola: passa a se chamar – Casos concluídos: caso finalizado com sucesso após a 4ª observação 
                - Incluir: Casos interrompidos: criança ou adolescente que  evadiu durante as etapas de observação e cujo caso não foi reaberto.

- Status do caso (como consta hoje): deixa de existir, pois os dados já foram incorporados no Status acima que definimos.

- Região: mudar nomenclatura para – Zona Rural / Urbana

- Colocar o filtro “Por último ano escolar cursado” (que está lá no fim da página) para Dimensão e retirar do filtro (ele só vai figurar em Dimensão e não vai mais ficar como filtro)

- Incluir em Dimensão: Região geográfica (norte, nordeste, sul, sudeste e centro-oeste)


2. Filtros
- Os filtros “Por status da criança” e “Por status do Caso” se fundem em um só, chamado agora de “Por status do caso”, usando os dados da nova dimensão acima descrita (de Status do Caso, com as 5 situações e suas novas nomenclaturas)

- Retirar os filtros: por motivo de caso, por etapa, por faixa etária, por sexo, por último ano escolar (conforme acima) e por zona. Estes filtros não são necessários, pois em Dimensão os dados já aparecem (fica repetitivo, polui e dificulta o uso da aba por parte dos usuários)

3. Outros
- Incluir a seguinte legenda para a (re)matrícula (que figura em etapas do caso): aguardando os dados de (re)matrícula serem inseridos
- Verificar possibilidade de criar botão de pesquisa flutuante.
