### ISSUE TITLE
Cruzamento dos dados meta do SELO UNICEF no relatório de usuários da Plataforma hasno dependencies

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#457]
Cruzamento dos dados de usuárixs da plataforma da BAE com a listagem dos municípios que fazem parte do Selo UNICEF (inclusão de uma coluna para identificação dos municípios do Selo UNICEF)

**Comment by manoelsouzaunicef** [comment]
Issue priorizada pela equipe no dia 18 de março
