### ISSUE TITLE
Criar perfil de visitante voltado para as Seccionais Undime e parceiros implementadores

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#458]
Criar perfil de visitante voltado para as Seccionais Undime e parceiros implementadores do Selo UNICEF por estado (cada usuárix só visualiza dados do seu respectivo estado). Essxs usuárixs serão cadastradxs e gerenciadxs pela equipe de gestão nacional. Esse perfil apenas visualiza (não pode alimentar o sistema) as seguintes informações: aba painel, aba relatórios, aba usuários (constar apenas nomes e contatos de gestorxs políticxs e coordenadorxs operacionais), aba municípios (listagem dos municípios, por cada estado, que aderiram).

**Comment by manoelsouzaunicef** [comment]
Mudar nome para perfil visitante

**Comment by manoelsouzaunicef** [comment]
![perfil.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/c99824af-a08f-406a-ba48-fd321bba16d8)

**Comment by manoelsouzaunicef** [comment]
Solucao final:
![filtro.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/0ab4f129-7d90-421b-ac41-e5862ee44569)

![cadastro.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/ff8279a2-6845-42d8-bcb5-87ef890c514c)

**Comment by manoelsouzaunicef** [comment]
Perfis de testes:
perfil_um@estadual.teste.com
perfil_dois@estadual.teste.com
perfil_tres@estadual.teste.com
perfil_quatro@estadual.teste.com

perfil_um@nacional.teste.com
perfil_dois@nacional.teste.com
perfil_tres@nacional.teste.com
perfil_quatro@nacional.teste.com
