### ISSUE TITLE
Esclarecimento: inatividade

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#46]
Existe a possibilidade de verificar o que caracteriza a "inatividade" de um determinado município/estado? É a falta de login na plataforma? É a falta de produção de alertas? É a inoperância na gestão dos casos?

Gentileza verificar também o período considerado para que um município/estado se torne "inativo".

**Comment by manoelsouzaunicef** [comment]
Este tipo de alerta aparece na dashboard e no relatório xls. Inatividade está relacionado a ultima data de acesso. De acordo com a regra geral, aqueles municípios que não fizeram nada nos últimos 30 dias são considerados inativos. Inclusive fizemos a correcão deste item no arquivos xls.
