### ISSUE TITLE
3.2 Na aba Relatórios, remover o botão filtrar e deixar a ação de filtragem automática 

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#475]
A cada escolha de parâmetro de filtragem, a aplicação da opção no filtro deve ser realizada de forma automática, sem a necessidade de rolar a barra até embaixo e pressionar o botão Filtrar.

**Comment by manoelsouzaunicef** [comment]
Esse item foi modificado a pedido da equipe para manter o botão do filtro
