### ISSUE TITLE
Ajustar a ordenação do gráfico na dashboard para já aparecer pré-ordenado no login

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#477]
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/eeb0007f-a2c6-4ca0-bef4-67e5c1175e24)

**Comment by manoelsouzaunicef** [comment]
Finalizado
![Screen Shot 2020-04-07 at 19.03.16.png](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/0234a7b2-5171-496f-9b4b-cbe7b0d8180c)
