### ISSUE TITLE
Status dos casos cancelados

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#49]
Ambiente: teste
Perfil: Supervisor Institucional
Aba: casos (filtro "cancelado")
Melhoria: a redação do status deverá contemplar o motivo do cancelamento para facilitar a visualização

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/47238565-fd2f9f80-d3b8-11e8-9595-37ae96b2196e.png)

**Comment by manoelsouzaunicef** [comment]
Finalizamos essa tarefa, porém precisaremos fazer uma atualização nos 38 mil registros que existem na base de dados para atualizar os motivos dos cancelamento anteriores. 
O sistema do Busca Ativa Escolar utiliza uma base de dados MySQL e outra do Elasticsearch. Essa segunda é usada para registro de dados de relatórios e dados que requerem uma busca mais detalhada, como a lista de casos em andamento. Os dados atuais do elasticsearch não contém o motivo do cancelamento dos casos. Precisaremos, portanto, sincronizar as bases. 
Antes de dar início a esse processo, faremos o teste em máquinas aqui do Unicef. Quanto ao front, ele já pode ser validado.

![Screen Shot 2018-11-09 at 13.41.08.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454fa6b7191a379ec0c2f50415f46be5d4a1f06a3a3dc78e2a436628f0e5ab9d06d0c7c933e16f8b8811fbf53e820dd4d80b1ee9850d2aa6c7bb3d4d216744b470a83ed5c32aa984ecc59f14ce94c55a51a356af43b.png)
