### ISSUE TITLE
Gráfico de evolucao de (re)matriculas - Pesquisa de alternativas ao FusionChart;

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#512]

**Comment by sandyunicef** [comment]
https://apexcharts.com/javascript-chart-demos/column-charts/
https://developers.google.com/chart/interactive/docs/gallery/columnchart
https://www.fusioncharts.com/fusiontime/examples/column-and-line-combination-chart-on-time-axis?framework=angular
https://www.slant.co/topics/3890/~best-javascript-charting-libraries
https://observablehq.com/@d3/stacked-to-grouped-bars
https://www.slant.co/topics/3890/~best-javascript-charting-libraries
