### ISSUE TITLE
Bug: customização

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#53]
Na fase de customização, o sistema está aceitando desmarcar todos os grupos (pelo menos um deles deve ficar marcado para receber o alerta, se não este ficará no limbo)

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/47504473-b0c5e300-d842-11e8-92ca-77280512a189.png)

**Comment by manoelsouzaunicef** [comment]
Finalizamos essa etapa de validação desses grupos. Vale ressaltar que nessa semana fomos alertados pelo Ítalo e Júlia sobre a necessidade dessa configuração. Depois de uma análise mais detalhada decidiram que o grupo Secretaria Municipal de Educação deve permanecer marcado para todos os motivos de evasão escolar.

**Comment by manoelsouzaunicef** [comment]
Alerta exibido ao tentar salvar as configurações sem selecionar a Secretaria Municipal de Educação
![Screen Shot 2018-11-02 at 13.18.55.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b76226454f16b7191a379ec0c2a59415a4bbe5d4a1f06a3a3dc78e2a436628f0e5ab9d06d0c7c933e16f8b8811fbf53e820dd4d80b1ee9850d2aa6c7bb3d4d216744b470a83ed5f34aa984ecc59f74ce6455ca0113464f43b.png)
