### ISSUE TITLE
Melhoria: visualizar senha digitada (em todas as ocorrências de senhas ou campos com caracteres ocultos)

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#54]

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/47527703-8e02f100-d879-11e8-94d6-76d6a8104c33.png)

**Comment by biancacambiaghi** [comment]
Na tela de cadastro de usuários acho importante mostrar a senha, temos visto vários municípios fazendo confusão com essa questão da criação da senha para os usuários (não lembram ou não se atentaram para essa etapa). 

Já na tela de login na plataforma sugiro não mostrar a senha, pois muitos acessam à plataforma em encontros do comitê gestor usando projetor. Uma saída seria incluir um ícone de visualização da senha (geralmente é um par de olhos) caso seja necessário mostrar a senha.
