### ISSUE TITLE
Planilhas balanço municípios (ativos, inativos, aguardando configuração)!!!

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#58]

**Comment by manoelsouzaunicef** [comment]
De acordo com a Dani, os dados exibidos na planilha não batiam com os dados exibidos na dashboard do usuário do tipo Gestor Nacional. 

Os relatórios em questão são os emitidos na aba Municípios e na aba Adesões Municipais. O status ativo/ inativo não estavam corretos. A prova disso pode ser feita na coluna Último acesso. Mesmo com datas com períodos superiores a 30 dias, a coluna status apresenta o termo "Ativo".

**Comment by manoelsouzaunicef** [comment]
Fiz as devidas correções nas classes e funções relacionadas a emissão dos relatórios. 
Os relatórios podem ser baixados em Municípios e em Adesões Municipais. A primeira exibe todos os dados relacionados ao acesso dos municípios já aprovados e configurados. Esse arquivo não exibe os municípios que apenas fizeram a adesão. A segunda contém todos os municípios que fizeram adesão, aprovados ou não, configurados ou não.

**Comment by manoelsouzaunicef** [comment]
As correções foram colocadas em produção para análise dos dados reais.
