### ISSUE TITLE
Pesquisar se existem chaves de API ou senhas embedadas no código fonte

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#631]
The application code shall never contain any credentials.

**Comment by manoelsouzaunicef** [comment]
As chaves usadas na plataforma são das seguintes ferramentas:

**HERE API**
Na API está setada em VAR de ambiente
No front está no código. Essa chave é válida apenas para os dosmínios *.buscaativaescolar.org.br

**GOOLGLE MAPS (DESATIVADA)**

**ZENVIA**
Apnas em VAR de ambiente

**MAILGUN**
VAR de AMBIENTE na API
VAR de ambiente no front alert page

**Comment by manoelsouzaunicef** [comment]
Solução para salvar chave no front fora do código -> Usar um import de um arquivo não versionado

**Comment by manoelsouzaunicef** [comment]
Para não exibição da chave das APIS no front angular usamos servicos. O arquivo não está versionado e localicado em resources/assets/js/services/keys.js
