### ISSUE TITLE
Remover todas as contas padrão e senhas, bem como auditar e remover chaves criptográficas de acesso de pessoas que não precisam mais acessar a plataforma

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#634]
Encryption keys shall be securely stored outside of the systems on which they are used.

**Comment by manoelsouzaunicef** [comment]
Removemos todas as chaves de usuários antigos e renovamos as chaves relacionadas ao equipamento da equipe de desenvolvimento e as chaves dos servidores do CodeShip

**Comment by manoelsouzaunicef** [comment]
- Fazer cadastro dos usuários de gestão nacional
- Criar novas senhas para o ambiente

**Comment by manoelsouzaunicef** [comment]
Mudar senhas da homologação e produção e ativar o authentication na digital ocean

**Comment by manoelsouzaunicef** [comment]
1 - Desativação do Root Login com SSH
no arquivo /etc/ssh/sshd_config:
PermitRootLogin no


2 - Definir usuários com acesso SSH:
usar o user XXXX para as contas dos desenvolvedores e CI

no arquivo /etc/ssh/sshd_config:
AllowUsers XXX

4 - Habilitar apenas authencation com chaves
no arquivo /etc/ssh/sshd_config:
PasswordAuthentication no

5 - Reiniciar SSH
/etc/init.d/ssh restart
