### ISSUE TITLE
Atribuir responsável

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#65]
Quando abre esse campo, aparece apenas o nome da pessoa e a função (técnico, supervisor, etc.). Sugeres-e que apareça nome, função, grupo.

Segundo município solicitante, esta medida  ajudaria bastante no caso de muitos técnicos e várias Secretarias envolvidas.

**Comment by biancacambiaghi** [comment]
Na plataforma teste isso já está implantado.

![grupo.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46ef868f338dc1e5cdf9ad4cae58f3806b1c65262b05a77a2086bb2dec157f515c5f4efe13580946f9fedb39baa47e21d40854b088270a36d43703adbf881eba05b9258a4784b5be8849c7fa70.jpg)

**Comment by biancacambiaghi** [comment]
Já foi publicado no ambiente de produção?
