### ISSUE TITLE
2 a 5 Novo Fluxo Pedido de Adesão/Readesão

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#664]
Prefeito (ou alguém indicado por ele) clica no botão novo de adesão, no site BAE, e aparece um dashboard para inserção dos seus dados e para fazer upload de documento que contenha CPF.
 

Novo município participante

Graphical user interface, text, application, email

Description automatically generated

 

Seleção de UF e  município

Graphical user interface, text, application, email

Description automatically generated

 

Cadastro do prefeito – Hoje é a etapa 3 – Será a etapa 2

Graphical user interface, application

Description automatically generated

 

- Iremos incluir os campos Título de eleitor e botão de upload de um documento com foto, no exemplo acima.

 

Ao inserir os dados e realizar o upload do documento com foto, o requisitante irá efetuar o cadastro do Gestor Político: aparece o dashboard para inserção dos dados do gestor político.
 

Mesmo processo que existe hoje na etapa 2 – Será a etapa 3

Graphical user interface, text, application, email

Description automatically generated

 

Cadastra ou altera sua senha com as novas orientações de segurança necessárias e assina termo de uso de dados da plataforma. Com a readesão, o município se compromete com todos os casos que estão em andamento e que estão atrelados às diversas funções e não pessoas.
 

Um detalhe importante e que passou despercebido aqui: Neste momento não existem tenants/munícipios cadastrados. E pela lógica da plataforma não temos usuários e senhas registradas nesse momento. Isso pode ser resolvido na etapa 8/9. Por enquanto a plataforma registra apenas um tabela de adesões pendentes (tenants/sigunps).

 

Após a assinatura do termos de uso, e confirmação da solicitação de adesão, enviaremos um email automaticamente para o endereço indicado pelo candidato no site do TSE, informando que foi realizada solicitação de adesão ao BAE em seu nome e com um link para confirmar e outro para reportar que não foi ele quem autorizou ou fez a tentativa de adesão.
 

Termo de adesão

Graphical user interface, text, application, email

Description automatically generated

**Comment by sandyunicef** [comment]
Para mais informações verificar e-mail:
Daniel Barboni
Qua, 21/10/2020 14:55

**Comment by manoelsouzaunicef** [comment]
Etapas:
**OK ->** 1 - Mudança da ordem no cadastro do gestor e prefeito;
**OK ->** 2 - Criação de um controlador para recebimento dos arquivos de upload;
**OK ->** 3 - Atualização do cadastro de tenants signups com novos campos (titulo e link do documento no Storage da API);
**OK ->** 4 - Exibição do título na tela de Adesões pendentes;
**OK ->** 5 - Exibição da imagem com link do documento na tela de adesões pendentes

**PROSSEGUINDO PARA NOVA ISSUE. PROCEDIMENTO COM MUITAS ETAPAS**
