### ISSUE TITLE
Função "relatórios": Municípios solicitam a possibilidade de poder visualizar os alertas e casos cancelados

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#67]
Municípios solicitam a possibilidade de poder visualizar os alertas e casos cancelados

**Comment by biancacambiaghi** [comment]
Também recebemos essa demanda: que o coordenador operacional e supervisor institucional consigam consultar o histórico de ALERTAS cancelados. 

Pelo que entendi os CASOS cancelados ficam na aba PAINEL e com o motivo indicado, certo?

**Comment by manoelsouzaunicef** [comment]
@biancacambiaghi e @Vilmar72
Atualmente os alertas que foram rejeitados aparecem na tela de casos. Eles podem ser encontrados quando fazemos um filtro por "Status do alerta: Rejeitado + Status do caso: Cancelado". Não faz muito sentido ter esse tipo de filtro de alertas na tela de casos, pois nem todo alerta chega a etapa de um caso.
Sugerimos remover esse filtro do relatório de casos:
![Screenshot 2018-12-11 at 15.53.51.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7855e32a64c5b27df117284f5a5e5cb053181d1ba6acda6fb4bc2e75d80d5fecd13e5721c53a45acbb821fed53ba76894a82e4ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fcc5df34be94853a0113f71ab.png)
E exibir os alertas que foram rejeitados na tela de alertas (hoje com o nome de alertas pendentes). A página terá o nome de alertas e não alertas pendentes. A intenção é que exiba os alertas pendentes de aprovação e que exiba aqueles rejeitados através de um filtro
![Screenshot 2018-12-11 at 15.56.21.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7855e32a64c5b27df1172d4f5d5e5cb053181d1ba6acda6fb4bc2e75d80d5fecd13e5721c53a45acbb821fed53ba76894a82e4ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fcc5df34ae14f57a5113171ab.png)

**Comment by biancacambiaghi** [comment]
Acho então que justamente pelo fato do filtro de alerta rejeitado estar na aba de casos é que ele "não funciona". Digo não funciona porque sabemos que temos mais de um alerta rejeitado no nosso município fictício na plataforma teste e só aparece um alerta. Também achei ruim (não é intuitivo) ter que selecionar DOIS filtros para achar essas ocorrências (alerta rejeitado + caso cancelado).

Achamos sua sugestão de solução ótima. Uma aba de alertas e que nela conste tanto os pendentes quanto os rejeitados.
