### ISSUE TITLE
12 - Tela de usuários Coordenador Oparacional

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#673]

**Comment by sandyunicef** [comment]
![image.png](https://images.zenhubusercontent.com/5cd96f8fee941c07853fb447/e6db097e-feb5-4b42-8828-b0e092035385)

**Comment by manoelsouzaunicef** [comment]
Criar uma função que reenvie a mensagem de **Reativacao**
Algo semelhante já feito em **Tenant->provision e Tenant->recovere**

Acredito que esse link pode estar presente na coluna das edicoes dos dados do usuário

**Função disponível apenas para gestores que podem fazer edicoes de usuários**

**Comment by manoelsouzaunicef** [comment]
![Annotation 2020-12-05 170551.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/0fa7d369-4ab4-4d34-95b3-ffc3bc6b95c2)
