### ISSUE TITLE
13, 14,15,16 - Recebimento de email e assinatura de Termos usuários do sistema

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#675]
13 -Os Supervsores Institucionais recebem email para acessar a plataforma. No primeiro acesso, deverão assinar o termo de uso de dados da plataforma, cadastrar ou alterar sua senha com as novas orientações de segurança necessárias e atualizar seus dados.
 

14 - Supervisores Institucionais acessam a aba usuários e fazem a checagem dos técnicos verificadores e agentes comunitários ligados especificamente às suas áreas: podem desativar antigos e cadastrar novos ou manter os mesmos. Essa função pode ser deles ou do CO, a depender de como o município definir. Clicam em botão novo para envio de mensagem aos TVs e ACs para que estes acessem a plataforma.
 

15 -TVs: Recebem email para acessar a plataforma. No primeiro acesso, deverão assinar o termo de uso de dados da plataforma, cadastrar ou alterar sua senha com as novas orientações de segurança necessárias e atualizar seus dados.
 

16 - ACs: Recebem email para acessar a plataforma. No primeiro acesso, deverão assinar o termo de uso de dados da plataforma, cadastrar ou alterar sua senha com as novas orientações de segurança necessárias e atualizar seus dados.
 

A ideia aqui é que a cada cadastro ou ativação de usuário já desativado, ele deverá aceitar o termo. A plataforma não tem nada nesse sentido de telas para aceitação desse tipo. Sugiro um envio de email para cada usuário com as opções para aceitar ou não o termo. Clicando em não aceitar, esse usuário permanece desativado.

![image.png](https://images.zenhubusercontent.com/5cd96f8fee941c07853fb447/404ee1a1-82fe-4579-a6f5-22a9d76c295a)

**Comment by manoelsouzaunicef** [comment]
Já existe um processo de envio de emails para os **Coordenadores recuperados** e o **coordenador novo**. Ainda precisamos editar a função que faz o registro dos usuários da plataforma para que envie o link para quaquer tipo de cadastro.

Um exemplo do processo está em **Tenant->provision e Tenant->recovere**

Ex: 
**Mail::to($user->email)->send(new UserRegisterNotification($user, UserRegisterNotification::TYPE_REGISTER_INITIAL));**
