### ISSUE TITLE
Função "filtro"

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#68]
Município sugere possibilidade de filtrar pelo usuário os alertas/casos que foram enviados, aceitos e encaminhados

**Comment by manoelsouzaunicef** [comment]
@Vilmar72
Essa questão já foi resolvida em outras issues. Tanto a lista de alertas pendentes como a lista de casos em andamento. Ambas têm um campo para busca por palavras chaves
![Screenshot 2018-12-11 at 15.28.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7855e32a64c5b27df110234f5e565cb053181d1ba6acda6fb4bc2e75d80d5fecd13e5721c53a45acbb821fed53ba76894a82e4ae965e82b96371b8d6d6056b5c17129bfe553fa19c4fcc5df242e24e50a31a3f71ab.png)

**Comment by manoelsouzaunicef** [comment]
![Screenshot 2018-12-11 at 15.29.20.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bab9e2f456b3b0011bea9a9/125516c66e82c728ace21e0d46db978826878dba87e6ab03f60da1cc6417753e7855e32a64c5b27df110224f5d5f5cb053181d1ba6acda6fb4bc2e75d80d5fecd13e5721c53a45acbb821fed53ba76894a82e4ae965e82b96371b8d6d6056b5c17129bfe5a3fa19c4fcc5df242e24557a1133671ab.png)
