### ISSUE TITLE
Inclusão campo "idade" nas etapas de alerta e de pesquisa

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#69]

**Comment by biancacambiaghi** [comment]
Sugestão de incluir dois campos distintos: 
- idade do cadastro: preenchimento do usuário na etapa de alerta (campo não obrigatório) e pesquisa (campo obrigatório)
- idade atual: preenchimento automático da plataforma a partir da data de nascimento (só apareceria na etapa de pesquisa)

**Comment by danielbarboni** [comment]
Após alinhamento com Bianca, ficou definido que não é necessário incluir idade na fase de alerta, dado que já existe um campo de observação.

**Comment by danielbarboni** [comment]
Quanto à idade atual não daria para comparar com a data do alerta porque o campo não é obrigatório na fase de alerta.

**Comment by danielbarboni** [comment]
Verificar como está implementada na plataforma o campo com o cálculo da idade que aparece nas abas painel e casos.

**Comment by biancacambiaghi** [comment]
Essa issue está paralisada, mas os municípios tem questionado como a IDADE que aparece no painel é calculada. Se com base na data do alerta ou do dia corrente. Podem verificar por favor?

**Comment by danielbarboni** [comment]
Incluir o cálculo automático de idade quando for preenchida a data de nascimento na etapa de Pesquisa

**Comment by danielbarboni** [comment]
Após discussão final com representantes do grupo de Educação, foi acordado que sta feature será ajustada para que em todo e qualquer campo data, ao o usuario colocar o mouse sobre a mesma, aparecerá um texto informando quanto tempo se passou (por extenso), desde a data específica, até a data atual, por exemplo, "seis anos, 4 meses e 25 dias).

**Comment by manoelsouzaunicef** [comment]
Locais onde identificamos as datas que serão substituídas![datas.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/4e0ccba9-f64c-44da-995c-ff73c212387f)
