### ISSUE TITLE
Separar as categorias "pretos" e "pardos"

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#70]
Segundo IBGE as categorias para cor/raça são: amarela, branca, indígena, parda e preta (não negra).

**Comment by manoelsouzaunicef** [comment]
Aguardando orientação da equipe do busca ativa para saber o que fazer com os casos já cadastrados.

**Comment by manoelsouzaunicef** [comment]
Decidimos colocar apenas o termo Pretos e pardos. Não criar uma nova opção.
