### ISSUE TITLE
11 - Atualização dos dados e criação de nova senha forte

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#719]
Após aceitar o termo da LGPD o usuário deve revisar seus dados cadastrais e cadastrar ou alterar sua senha com as novas orientações de segurança necessárias e atualizar seus dados.

**Comment by manoelsouzaunicef** [comment]
Tela para confirmacao de cadastro está pronta. Regra de senha forte deve ser implementada nos campos de senha no momento de **configuracao da adesao** e na tela de **confirmacao de dados do usuário**

**Comment by manoelsouzaunicef** [comment]
![Annotation 2020-11-26 174726.jpg](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/8523def4-776d-44e1-af6c-6445c9f58305)

**Comment by manoelsouzaunicef** [comment]
Rafael finalizou os campos com senha forte
