### ISSUE TITLE
Criação do Active Directory no Azure AD B2C

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#722]

**Comment by rafaelecs1** [comment]
1 - Criação do Locatário AD B2C do UNICEF no portal do Azure.
2 - Criação do domínio do locatário baunicef (ba = busca ativa) para o projeto do Busca Ativa Escolar.
3 - Alteração na página de acesso nos fluxos de usuários para incluir o logo do Busca Ativa Escolar e o banner do UNICEF.
4 - Registro da aplicação responsável por fazer a requisição do token de acesso, sem intermédio de usuário, para acesso à API do Microsoft Graph. Microsoft Graph será responsável pelo parte de criação, edição e desativação dos usuários no AD B2C.
5 - Escolha do método de autenticação através do fluxo de usuários ROPC (Resource Owner Password Credentials flow). Essa escolha foi feita com base na necessidade de um primeiro momento não ser utilizado a tela de login da Microsoft.
6 - Registro da aplicação responsável por permitir que o fluxo de usuários ROPC possa ser utilizado. Esse fluxo permite que usuários registrados no AD possam fazer a autenticação na plataforma e validar o token de acesso.
7 - Alterações nas permissões de acesso e escrita da aplicação responsável pelo gerenciamento de usuários com a API Microsoft Graph.
