### ISSUE TITLE
Criação da aplicação de comunicação com o AD.

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#723]

**Comment by rafaelecs1** [comment]
1 - Criado nas variáveis de ambiente do projeto os valores padrão da chamada para a aplicação que faz o ROPC.
2 - Criado o arquivo de configuração na API do Busca Ativa Escolar.
3 - Criado o controller que valida as credenciais de acesso do usuário no AD B2C.
4 - Modificação do controller de autenticação IdentityController para permitir que apenas usuários que existam no AD e no banco possam acessar a plataforma.
5 - Criado nas variáveis de ambiente do projeto os valores padrão da chamado para a aplicação que faz a comunicação com a API do Microsoft Graph.
6 - Criado o arquivo de configuração na API do Busca Ativa Escolar.
7 - Criado o controller que pega o token de acesso para a API do Microsoft Graph.
8 - Criado o método para inserção de usuários no AD.
9 - (Em andamento) Criado o método para edição de usuários no AD.
10 - (Em andamento) Criado o método para desativação de usuários no AD.
11 - (Futuro) Implementar os métodos em todas as rotas que insiram, alteram ou desativem usuários.
