### ISSUE TITLE
Lista de municípios que fizeram adesão

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#73]
Existe algum local onde os municípios podem consultar quais são os outros municípios brasileiros que fizeram adesão ao BAE?

**Comment by manoelsouzaunicef** [comment]
@biancacambiaghi  acredito que a tela da Dashboard do Landing Page resolva isso. Na página de teste está em https://site.testes.buscaativaescolar.org.br/municipio.html

**Comment by biancacambiaghi** [comment]
Ótimo, daremos essa orientação aos municípios. Mas só me confirma, essa tela já foi para o ambiente de produção?
