### ISSUE TITLE
Como vai ficar a alteação de senha pelo Gestor, Coordenador e demais perfils.

### ISSUE THREAD

**Issue by sandyunicef** [UNICEF01/BuscaAtiva#744]
Verificar a troca de senha do próprio usuário e a alteração de senhas pelo gestor coordenador e etc.

**Comment by sandyunicef** [comment]
![image.png](https://images.zenhubusercontent.com/5cd96f8fee941c07853fb447/54d942ec-4877-475c-832f-de735e88b4d5)

**Comment by manoelsouzaunicef** [comment]
Usuários fazem a mudança da própria senha. Não existe mais a senha temporária.

1 - Usuários do tipo **gestão nacional, supervisão estadual, coordenação estadual, membros de comitês e visitantes nacionais e estaduais** não passam por processo de readesão. Estes serão redirecionandos para tela de **lgpd_signup** para cadastro de novas senhas.;

2 - Usuários de municípios:
**Gestor político** define a senha no processo de readesão;
**Coordenadores** definem a senha através do email que recebem no final da adesão/readesão (Se não receberem, o gestor pode reencaminhar na lista de usuários);
**Supervisores institucionais, Técnicos verificadores e Agentes comunitários** recebem email de ativação. (Se não receberem, o gestor  ou coordenador pode reencaminhar na lista de usuários);

Os usuários também podem pedir a redefinição de senha na tela inicial ou após logado.
