### ISSUE TITLE
Implementar no painel principal o quatitativo de municípios readeridos e manter os dados do ciclo anterior do Selo UNICEF

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#748]
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/36b7787a-52b4-46cf-9e3b-3620856bbff7)

**Comment by manoelsouzaunicef** [comment]
Decisão do dia 19 de janeiro:
Fazer histórico do uso da plataforma para todos os campos. No caso de adesões, apenas o que ocorreu, os demais fazer incremental
