### ISSUE TITLE
TSE - Importação dos dados sobre deficiência

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#752]

**Comment by manoelsouzaunicef** [comment]
Aguardando dados de 2017

**Comment by manoelsouzaunicef** [comment]
Solicitação feita a pedido do ítalo no dia 12/01/2021

**Comment by manoelsouzaunicef** [comment]
Arquivos compartilhados em 14//01/2021
Processo de criação de caches iniciado as 14h
