### ISSUE TITLE
Atualizar troca de gestor político e coordenadora operacional

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#76]
No login de membro do comitê nacional, em alguns municípios o gestor político ou coordenador operacional aparecem em vermelho mesmo sabendo que já houve troca dos profissionais. 

A solicitação é que o sistema seja atualizado com indicação do nome dos novos profissionais

Exemplos: Rio Bonito, Queimados e Rio de Janeiro (que solicitou expressamente que o antigo gestor político não conste na plataforma).

Na plataforma dos municípios entendemos que é preciso manter o usuário em vermelho, pois podem ter casos relacionados a ele. Mas na plataforma do membro do comitê nacional, os novos profissionais não aparecem

**Comment by biancacambiaghi** [comment]
![troca nome.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46fc86952083c3a780e4ba01e81fe086264c22703d46f9692587e22cee1278590a5c49f8415b5f44aeab897da4b33b22984019af80330b2b9b645bf9fa9015ad00b32a8a4a81b4b48a48c8e03c27e58b9d02.png)

**Comment by biancacambiaghi** [comment]
A issue 34 se refere à plataforma dos municípios.

**Comment by sandyunicef** [comment]
Issue resolvida anteriormente pelo @manoelsouzaunicef
