### ISSUE TITLE
Permitir exclusão e edição de anotação

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#78]
Permitir exclusão e edição de anotação feita pelo próprio usuário.

**Comment by biancacambiaghi** [comment]
Hoje só é possível incluir, mas municípios solicitam essa possibilidade (desde que ela fique registrada na aba de "histórico" do caso.

![anotacoes.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46e99a95378380a68afafd0fe64de29b234324676b5ee17e7284e779ef4123045c581aac42585f16aef9df29a3b16e62964e49bc8f3900299f7744eeaa880dbe09b0218e4b87bebc8d49c6eb3c27ef99c2.png)

**Comment by danielbarboni** [comment]
Permitir excluir ou editar, mas apenas o " dono" do comentário pode fazer isto.

**Comment by biancacambiaghi** [comment]
Isso, somente o usuário que inseriu o comentário poderia mexer nela. 

Nós sugerimos excluir, mas de repente a permissão possa ser apenas editar. Acho interessante envolver os outros nessa decisão.
