### ISSUE TITLE
Pesquisa adesões municipais (rejeitado versus adesão refeita e aceita)

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#80]
Quando o município erra o preenchimento do formulário de adesão, rejeitamos o pedido e pedimos a ele que refaça. Estando tudo OK, aceita-se a adesão e o nome do município saí da aba MUNICÍPIOS (figura 1). Depois que o município nomeia o Gestor e o Coordenador, passa a constar da aba USUÁRIOS. Problema que algumas pessoas, quando verificam a adesão de algum município, acessam apenas a aba MUNICÍPIOS e lá vêem que este consta como "rejeitado".

Temos que pensar num modo para que passe a constar as duas informações da adesão - tanto a que foi inicialmente rejeitada, quanto a que foi aceita...

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/48948207-e2ea6380-ef1a-11e8-8ea4-42396c312754.png)

FIGURA 1

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/48948247-fd244180-ef1a-11e8-980f-df05cc50c78a.png)

FIGURA 2

**Comment by manoelsouzaunicef** [comment]
@Vilmar72 Essa questão será resolvida na issue #102
