### ISSUE TITLE
Informações ao gerar um Alerta

### ISSUE THREAD

**Issue by jcaligiorne** [UNICEF01/BuscaAtiva#837]
1) Nos relatórios, em raça/etnia, onde está Preta, substituir por Negra. Fica assim: Negra (pretos e pardos)

2) Apresentar daqui para frente as opções de raça/etinia de acordo com o IBGE: Preta, Parda, Amarela, Indigena e Branca.

**Comment by manoelsouzaunicef** [comment]
1) Nos relatórios, em raça/etnia, onde está Preta, substituir por Negra. Fica assim: Negra (pretos e pardos)

1 - Criar novo campo **negra_pretos_pardos** nos tradutores
resources/lang/en/child.php
resources/lang/en/reports_terms.php

2 - Editar a traduçao de **preta** ( **Preta (pretos e pardos)** para **Preta** ) em 
resources/lang/en/child.php
resources/lang/en/reports_terms.php

3 - Cadastrar parda em app/Data/Race.php

4 - Criar traduçao de parda em 
resources/lang/en/child.php
resources/lang/en/reports_terms.php

3 - Fazer o update no banco de dados
update case_steps_pesquisa set **race**="negra_pretos_e_pardos" where race="preta"
update case_steps_alerta set **race**="negra_pretos_e_pardos" where race="preta"
update case_steps_pesquisa set **guardian_race**="negra_pretos_e_pardos" where guardian_race="preta"

5 - Fazer a reindexação das 500 mil criancas/ adolescentes no Elasticsearch (nó children)

6 - Instalar plugins de edição do elasticsearch da produção

script.engine.groovy.inline.search: on
script.engine.groovy.inline.update: on

7 - Fazer o update do children_daily para todos os docs com "race":"preta"

ANTES DO UPDATE - ATIVAR PLUGINS DO ELASTIC
script.engine.groovy.inline.search: on
script.engine.groovy.inline.update: on

CHAMADA DA ROTA PARA EDICAO
POST /children_daily/_update_by_query

{
  "script": {
    "inline": "ctx._source.race = 'negra_pretos_e_pardos'"
  },
  "query": {
    "match": {
      "race": "preta"
    }
  }
}

{
  "script": {
    "inline": "ctx._source.guardian_race = 'negra_pretos_e_pardos'"
  },
  "query": {
    "match": {
      "guardian_race": "preta"
    }
  }
}

**Comment by manoelsouzaunicef** [comment]
Issue com muitas ações. Nova issue para o ítem 3 da descrição:

Incluir um campo para preenchimento de nacionalidade. O botão ficaria assim:
Nacionalidade: Brasileira / Outra (aqui queremos a opinião de vcs se seria melhor deixar o campo aberto para escreverem ou se abrimos um dropdown com lista de países, o que tb seria bem grande).

**Comment by manoelsouzaunicef** [comment]
Correções dos ítens 1 e 2 no ambiente de testes
