### ISSUE TITLE
Diferenciar adesão/ readesão na planilha de novas adesões municipais

### ISSUE THREAD

**Issue by jcaligiorne** [UNICEF01/BuscaAtiva#839]
Atualmente, não é possível identificar quando um municípios está aderindo pela primeira vez ou se está readerindo à estratégia. Seria importante ter essa diferenciação para sabermos como abordá-lo.

**Comment by danielbarboni** [comment]
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/b48b13d6-f6af-4047-b97b-d4e786ecc1c9)

Inserir na planilha de exportar adesões municipais,  duas colunas contendo se o mesmo faz parte de qual ciclo da estratégia.
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/5ee4a6cd-e423-413e-b88f-4f2b730b2664)
