### ISSUE TITLE
Relatórios: cruzamento de dados em períodos específicos

### ISSUE THREAD

**Issue by jcaligiorne** [UNICEF01/BuscaAtiva#841]
Possibilidade de cruzar diferentes dimensões (idade, sexo, rural/urbano, etc) para períodos de tempo precisos. 
Ex: De 1/Janeiro a 13/Abril: quantidade de rematrículas de meninas e meninos, rurais e urbanos, etc.

**Comment by danielbarboni** [comment]
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/757b81ed-3a0d-49f3-bdb9-483b5b5e7644)
