### ISSUE TITLE
Permitir emissão de relatórios por usuários com perfil de Visitante estadual

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#844]
Descrição: As seccionais se cadastram como visitantes e não aparece essa opção para eles, era importante eles conseguirem, principalmente, o relatório de municípios.

![municipios visitantes.png](https://images.zenhubusercontent.com/5cd97033ee941c07853fb448/c089942b-8b63-4140-aa1b-4fe7762f804a)

**Comment by DalvaBAE** [comment]
Precisa criar no perfil visitante estadual também o botão de "exportar"

![bae - consultar municípios.JPG](https://images.zenhubusercontent.com/6081c8fcfc91d89d95b03e2b/1b2cbb5e-c59d-47bb-b755-61903256efed)"
