### ISSUE TITLE
Informações ao gerar uma Pesquisa

### ISSUE THREAD

**Issue by jcaligiorne** [UNICEF01/BuscaAtiva#847]
1) Nos relatórios, em raça/etnia, onde está Preta, substituir por Negra. Fica assim: Negra (pretos e pardos)

2) Apresentar daqui para frente as opções de raça/etinia de acordo com o IBGE: Preta, Parda, Amarela, Indigena e Branca.

**Comment by manoelsouzaunicef** [comment]
**ítens 1 e 2 resolvidos na issue #837**

**Comment by manoelsouzaunicef** [comment]
**Ítens registrados na #895**

3) Quando usuário optar por indígena, abrir espaço para descrever qual etnia.

4) Ter também duas opções fechadas: vive em terra indígena / não vive em terra indígena.

5) Inserir um campo contendo a nacionalidade dos responsáveis: Brasileira/ Outra (aqui queremos a sugestão de vocês: melhor deixar esse campo aberto ou lançar um dropdown com a lista dos países, que também seria bem extensa).

[https://app.zenhub.com/files/138191691/59a47db1-fbb9-443c-9a04-e2d7a9c8520b/download](https://app.zenhub.com/files/138191691/59a47db1-fbb9-443c-9a04-e2d7a9c8520b/download)
