### ISSUE TITLE
Exportação de dados gerais por ano calendário

### ISSUE THREAD

**Issue by jcaligiorne** [UNICEF01/BuscaAtiva#853]
Queridos, para a avaliação da BAE, precisaremos de dados de todo o período de funcionamento da plataforma (desde 2017), especificando os anos de cada dado (super importante para a avalição de impacto).

**Comment by danielbarboni** [comment]
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/2dc5e93c-59e8-49b1-a327-4654811facb2)

Exportar dados por ano, contendo para cada município, um extrato mensal contendo os dados de Alertas, Casos e Rematrículas.

**Comment by danielbarboni** [comment]
1) Alterar os textos no seletor de Ciclo Selo | 2014 - 2020, para Ciclo Estratégia 2014-2020 (Status em 31/12/2020), e Ciclo Selo | 2021, para Ciclo Estratégia | 2021 - 2024 (Status atual).

2) Adicionar ao seletor as opções: Status dos casos em 31/12/2017, Status dos casos em 31/12/2018, Status dos casos em 31/12/2019.
