### ISSUE TITLE
Bug: contador adesões estaduais

### ISSUE THREAD

**Issue by Vilmar72** [UNICEF01/BuscaAtiva#86]
Temos 7 adesões aceitas e o contador está mostrando 8 aceitas e mais uma pendente, neste momento (esta pendente já foi rejeitada por erro, mas creio que demore um pouco pra atualizar o contador).

Fato é que, as adesões estaduais aceitas totalizam 7 e não 8.

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/49092983-5d342400-f24a-11e8-9c50-77b3476175f7.png)

**Comment by Vilmar72** [comment]
![image](https://user-images.githubusercontent.com/44234962/49093004-691fe600-f24a-11e8-8f92-18dd4dfc34cf.png)

**Comment by manoelsouzaunicef** [comment]
Na troca de emails com a equipe, o Vilmar pediu para considerar a questão como fechada.
"Creio que tenha sido alguma inconsistência temporária do sistema. De fato, agora a contagem está correta. Por gentileza, considere o assunto resolvido."
