### ISSUE TITLE
Atualizar a página da campanha no BAE

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#872]
From: Daniella Rocha Magalhaes <dmagalhaes@unicef.org> 
Sent: sexta-feira, 14 de maio de 2021 13:34
To: Daniel Barboni <dbarboni@unicef.org>
Cc: Bae Undime <bae@undime.org.br>; Julia Ribeiro <jribeiro@unicef.org>; Julia Caligiorne Santos <jcaligiorne@unicef.org>
Subject: troca arquivos aba campanha site BAE

Boa tarde Daniel,
Tudo bem? Tem uma demanda prioritária da Busca Ativa Escolar que não deu tempo de conversar na nossa reunião, mas que depois a Júlia Caligiorne já subiu para o inbox, junto com as outras que selecionamos para essa próxima sprint.
Explico: precisamos alterar algumas informações nos produtos da aba campanha ( os PDFs, 1card e 1 storie). Essa aba está fora do CSS e, portanto, a troca dos produtos só os desenvolvedores podem fazer. Os produtos a serem trocados seguem no link e no zip abaixo e a Bia pode apoiar e acompanhar quando eles forem fazer a ação.
Abs
Dani

https://drive.google.com/drive/folders/1WY_-SKD4n_aPefebc7M6IRHXHjIRlfE9?usp=sharing 

  CORRIGIDO CAMPANHA.rar 

Segue em anexo.

Att
Bia

-- 
EQUIPE BAE - Undime
www.buscaativaescolar.org.br

**Comment by rafaelecs1** [comment]
Olá Rafael, tudo bem??

Verifiquei todos os PDFs. Orientações, kit mídia e informações gerais estão ok.

No entanto ficou faltando atualizar os PDFs dos estados, esses que ficam no mapa do Brasil. Mandamos tudo junto na pasta zipada, eles estão na pasta "estados". Pode verificar se recebeu por favor?

Também precisamos trocar a capa do card e stories atualizados. Ao clicar nos dois, eles abrem o produto atualizado, mas quando olhamos no site está aparecendo a capa do antigo. Mando em anexo com a marcação indicando qual deve trocar. É possível fazer essa atualização?

Também é preciso atualizar  o texto que está em "entenda os desafios", envio em anexo também o print.  Apenas o primeiro parágrafo, trocar para:

Estima-se que, no Brasil, exista um contingente de 1,1 milhão de crianças e adolescentes de 4 a 17 anos fora da escola. Os dados são da Pesquisa Nacional por Amostra de Domicílios (Pnad) de 2019, realizada pelo Instituto Brasileiro de Geografia e Estatística (IBGE). Esse número corresponde a 2,7% das meninas e dos meninos dessa faixa etária – e todos(as) deveriam estar estudando.

Na pasta zipada também enviamos um spot, que precisa ser substituído. Envio em anexo um print indicando qual e o novo produto de áudio.

Qualquer dúvida me avise por favor

Att
Beatriz
