### ISSUE TITLE
Trocar a opção de Raça/Cor de Sem Informação, para Não Declarada

### ISSUE THREAD

**Issue by danielbarboni** [UNICEF01/BuscaAtiva#894]
![image.png](https://images.zenhubusercontent.com/5584285d4f7a08fbb7f34e1c/49ebeac6-9600-48bf-bcc5-fbddadd2a6dc)

**Comment by manoelsouzaunicef** [comment]
Em conversa com a Dani na manhã do dia 24, ficou decido mudar apenas o termo **Sem informação** para **Não declarado** no select Raça/ Etnia
