### ISSUE TITLE
Atualização do relatório do SELO para os novos valores das metas.

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#898]
Verificar quantidade de alertas aprovados em relacção aos casos em andamento
Verificar calculos das metas exibidas nos graficos
Verificar regra para municípios que assinaram o termo em relação aos casos cancelados

**Comment by manoelsouzaunicef** [comment]
Está relacionado a issue #1378

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/898?planning-poker) with Zenhub @manoelsouzaunicef
