### ISSUE TITLE
Campo nacionalidade da criança

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#899]
5) Inserir um campo contendo a nacionalidade da criança/ adolescente
(Alerta e Pesquisa - Com dimensão no Gráfico) 

Foi decidido que usaremos uma lista com opções

**Comment by rafaelecs1** [comment]
Criar campo nacionalidade da criança na tela de criação de um alerta.
Criar campo nacionalidade da criança na tela de alertas pendentes.
Criar campo nacionalidade da criança na tela de dados consolidados para alerta.
Criar campo nacionalidade da criança na tela de evolução do caso para alerta.
Criar campo nacionalidade da criança na tela de evolução do caso para pesquisa.

**Comment by rafaelecs1** [comment]
Criar migration para inserir coluna nacionalidade da criança na tabela case_steps_alerta.
Criar migration para inserir coluna nacionalidade da criança na tabela children.

Criar campo nacionalidade da criança na tela de criação de alerta pelo aplicativo.
Criar campo nacionalidade da criança na tela de criação de alerta na página alerta.

**Comment by rafaelecs1** [comment]
Alterar a mensagem que é enviada via SMS.
