### ISSUE TITLE
Dúvida: obrigatoriedade Educação em todos os motivos

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#90]

**Comment by biancacambiaghi** [comment]
Na plataforma teste o grupo da Educação é obrigatório na visualização e notificação de todos os motivos. Queria saber se isso já foi pro ambiente de produção. E como foi processo de transição para os municípios que antes estavam configurados diferente.

**Comment by biancacambiaghi** [comment]
![sme.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5be5b541faa8400011d3fb14/125516c66e82c728ace21e0d46fb999f61cec1b99de6b546a749b2ce6b1325722d55f3282880b07fbb1228515f0d1cac175a5a43aeeb9539e4e76224d50152a7842f4d7ed43f10a6b9871bbc04bb28884784bfbd8e5e8d.jpg)

**Comment by manoelsouzaunicef** [comment]
@biancacambiaghi Isso também já foi colocado em produção. Os municípios que já tinham uma configuração definida permanecem com as configurações antigas. Serão alteradas apenas se tentarem definir novas regras. Discutimos isso no final da Segunda Sprint, mas não definimos se mudaríamos todas as configs antigas. É possível fazer, mas não sabemos se devemos prosseguir assim. Pode discutir com o Vilmar, Ítalo, Dani e os demais?

**Comment by biancacambiaghi** [comment]
Então se um município antes configurou que a Educação não iria visualizar determinado motivo, mesmo após a alteração na obrigatoriedade, a configuração se mantém a mesma e a Educação continua sem visualizar aquele motivo, é isso? Achávamos que automaticamente a Educação seria marcada em todos os motivos. Também não temos claro qual a melhor forma de prosseguir, mas foi uma dúvida que surgiu em determinado município que acompanhamos.

**Comment by danielbarboni** [comment]
Aguardando alinhamento de Vilmar e Dani com Italo e Julia acerca da alteração obrigatória de todos os municípios que haviam optado por não dar visibilidade dos motivos para a Secretaria de Educação. Em havendo a concordância, iremos proceder com a definição padrão para todos os municípios de que a Secretaria de Educação visualiza tudo e que isto não poderá ser alterado.

**Comment by daniellarocha** [comment]
colocar como padrão visualização e notificação da secretaria de educação para todos os municípios já configurados, inclusive para aqueles que anteriormente não haviam optado por isso.
