### ISSUE TITLE
Campo nacionalidade do responsável

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#900]
Inserir um campo contendo a nacionalidade dos responsáveis
Já existe o campo nacionalidade na parte de localizaçãona etapa Alerta e Pesquisa.
Verificar com a equipe de gestão se trata do mesmo assunto.
Verificar tabela antes da criação das migrations - Existem campos semelhantes

Se for novo campo considerar os seguintes requisitos:

- Verificar o JSON que fornece o formulário para o APP;
- Verificar processo de reindexação para registro de novos campos;
- Verificar necessidade de mapping do índice do elasticsearch para o registro dos novos campos;

> *Apos conversa com Dani*
> Apenas mudaremos de lugar o *campo de nacionalidade* que esta em *Dados de localização* e levar para os *Dados da criança ou adolescente*

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/900?planning-poker) with Zenhub @manoelsouzaunicef
