### ISSUE TITLE
Revisão dos campos da aba "Informações consolidadas"

### ISSUE THREAD

**Issue by biancacambiaghi** [UNICEF01/BuscaAtiva#91]

**Comment by biancacambiaghi** [comment]
Sugestão de rever os campos que aparecem na aba de Informações consolidadas do caso. Entendendo que são informações consolidadas e de rápido acesso, achamos que as informações necessárias ali são: nome da criança, data de nascimento e/ou idade, dados do responsável (nome), telefone, endereço e motivo da exclusão escolar (alerta e pesquisa). Assim, outras informações, se precisarem ser consultadas, serão procuradas na respectiva etapa em que foram coletadas.

**Comment by manoelsouzaunicef** [comment]
Não entendemos muito bem o motivo de limpar a tela com as informações consolidadas. Entendemos que essa tela é muito importante para os usuários da plataforma para ter uma visão geral das informações do caso. Forçar o usuário a navegar pelas etapas parece um pouco mais difícil. Seria interessante fazer alguns prints e indicar quais os campos são necessários, caso realmente tenhamos que mudar o layout dessa tela. @biancacambiaghi

**Comment by biancacambiaghi** [comment]
A sugestão não é limpar a tela e sim trocar alguns campos. Concordamos que é muito importante e por isso achamos que dados de cadastro como telefone e endereço precisariam constar nelas. Informações desse tipo são consultadas com mais frequência do que por exemplo a informação da criança trabalhar ou não.

**Comment by danielbarboni** [comment]
Alterações:
1) Ter os campos de contato consolidados entre diversas etapas.
2) Ao menos um responsável é obrigatório (mãe, pai, ou outro).
3) Inserir nome da mãe, RG, telefone de contato; nome do pai, RG, telefone de contato.
4) Indicar quem é o responsável (mãe, pai ou outro).
5) Se for indicado outro, pede nome, RG e telefone de contato.
6) Inserir botão que permita adicionar outros telefones de contato para cada um dos contatos inseridos (mãe, pai ou outro responsável).
![Busca Ativa2.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5bad106c499b870012b500ed/125516c66e82c728ace21e0d46ca81892083c3889be0a942f61fbcd6395428792c07b7692ac7b62abe462a510c571baf460c5f47fcf9db79a6e03e758d0e19f1c32f0e2a92624cf5f2d75dad0ba8228b4584b3b88e4bc2ee3824e78a884f2c53.PNG)

**Comment by danielbarboni** [comment]
7. Inserir a informação de endereço nas informações consolidadas.

**Comment by danielbarboni** [comment]
Na aba de informações consolidadas ter apenas as seguintes informações:
1) Dados da criança.
Nome, data de nascimento , sexo e endereço.
2) Dados do responsável
Nome e telefones de contato.
3) Motivos da exclusão da escola igual ao que aparece na análise técnica

**Comment by daniellarocha** [comment]
Revisamos a demanda com Julia ela pediu para incluir o item 4 abaixo:
Na aba de informações consolidadas ter apenas as seguintes informações:

1. Dados da criança.
Nome, data de nascimento , sexo e endereço.
2. Dados do responsável
Nome e telefones de contato.
3. Motivos da exclusão da escola igual ao que aparece na análise técnica
4. Última escola que estudou e último ano que cursou
