### ISSUE TITLE
BAE - criar campo nacionalidade da criança na tela de criação de alerta.

### ISSUE THREAD

**Issue by rafaelecs1** [UNICEF01/BuscaAtiva#944]

**Comment by rafaelecs1** [comment]
Front:
Criar o campo nacionalidade na tela de criação do alerta em create_alert.html
Alterar o arquivo static_data.js para criar a função que pega a nacionalidade da criança.

API:
Criar o arquivo Country.php que contém as nacionalidades. Servirá também para as nacionalidades dos responsáveis pela criança.

Alterar controller StaticDataController para incluir os countrys.

**Comment by manoelsouzaunicef** [comment]
Já está em produção
