### ISSUE TITLE
BAE - Erro na Dashboard pública com dados municipais

### ISSUE THREAD

**Issue by rafaelecs1** [UNICEF01/BuscaAtiva#948]
**Descrição:**

Ao utilizar a Dashboard publico da BAE e selecionar um município, ocorre um erro que impede a exibição das informações desejadas. O erro é indicado pelo código de status HTTP 404 (Not Found) ao fazer uma requisição GET para o seguinte endpoint: https://api.buscaativaescolar.org.br/api/v1/reports/report/city?ibge_id=4300554.

> Informações não aparecem em nível municipal
> https://buscaativaescolar.org.br/municipios
>
> **GET** https://api.buscaativaescolar.org.br/api/v1/reports/report/city?ibge_id=4300554
> _404 Not Found_
>
> O erro ocorre quando seleciona um município

![WhatsApp Image 2023-06-20 at 17.07.36.jpg](https://images.zenhubusercontent.com/6238de3ad16134773fdd2395/794a7e01-9cbc-4665-bc5f-701b96300de2)

**Comment by manoelsouzaunicef** [comment]
Relacionada a issue #1378
A nacionalidade está no campo de localização e não da criança

**Comment by ricardosreichert** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/BuscaAtiva-5cd96f21ee941c07853fb440/issues/UNICEF01/BuscaAtiva/948?planning-poker) with Zenhub @manoelsouzaunicef
