### ISSUE TITLE
Sistema de pesquisas - Rotas na API para gerenciamento de tipos de usuários

### ISSUE THREAD

**Issue by manoelsouzaunicef** [UNICEF01/BuscaAtiva#978]
Rota para uso do perfil admin para criação e edição de usuários

**Comment by princebsb** [comment]
Foram criados os recursos para o gerenciamento dos usuários.

As seguintes APIs:

GET Authenticated - Usuários -> api/admin/usuarios
* Lista todos os usuários cadastrados no sistema

GET Authenticated - Usuários -> api/admin/usuarios/{id}
* Lista dados de um determinado usuário

PUT Authenticated - Usuários -> api/admin/usuarios/{id}
* Modifica dados de um determinado usuário

DEL Authenticated - Usuário -> api/admin/usuarios/{id}
* Deleta (softdelete) um usuário determinado.
